/**
 * MavinEngine Native Module Wrapper
 *
 * Single source of truth JS/TS bridge.
 * Every function maps 1-to-1 to an AsyncFunction in MavinEngineModule.kt.
 *
 * Kotlin module name:  "MavinEngine"
 * Extractor version:   NewPipeExtractor 0.26.0
 *
 * Service IDs (NewPipe standard):
 *   0 = YouTube
 *   1 = SoundCloud
 *   2 = media.ccc.de
 *   3 = PeerTube
 *   4 = Bandcamp
 */

import { requireNativeModule } from 'expo-modules-core';

// ─────────────────────────────────────────────
// Native Module
// ─────────────────────────────────────────────

const Native = requireNativeModule('MavinEngine');

if (!Native) {
  console.error('[MavinEngine] CRITICAL: native module not loaded.');
}

// ─────────────────────────────────────────────
// Shared sub-types
// ─────────────────────────────────────────────

export interface NativeImage {
  url: string;
  width: number;
  height: number;
  resolutionLevel: 'UNKNOWN' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
}

/**
 * Pagination cursor returned by the Kotlin layer.
 * When there is no next page, this is an empty object `{}`.
 * Always use `hasNextPage` to check for more pages.
 * 
 * Kotlin Page class uses getters: getUrl(), getIds(), getCookies()
 * but expo-modules-core converts these to plain object fields.
 */
export interface NativePage {
  url: string;
  ids: string[];
  cookies: Record<string, string>;
}

// ─────────────────────────────────────────────
// Stream types (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * AudioStream fields (v0.26.0):
 * - getBitrate() returns int (was getAverageBitrate() pre-v0.22.0)
 * - getAudioTrackId(), getAudioTrackName(), getAudioLocale(), getAudioTrackType()
 */
export interface AudioStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  /** v0.26.0 uses getBitrate(), NOT getAverageBitrate() */
  bitrate: number;
  audioTrackId: string;
  audioTrackName: string;
  audioLocale: string;
  /** AudioTrackType enum name or empty string */
  audioTrackType: string;
  manifestUrl: string;
}

/**
 * VideoStream fields (v0.26.0):
 * - getWidth(), getHeight(), getFps(), getBitrate(), getQuality()
 * - NO getAverageBitrate() - use getBitrate()
 */
export interface VideoStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  width: number;
  height: number;
  fps: number;
  /** v0.26.0 uses getBitrate(), NOT getAverageBitrate() */
  bitrate: number;
  manifestUrl: string;
  quality: string;
}

/**
 * SubtitlesStream fields (v0.26.0):
 * - getLanguageTag() returns BCP-47 language tag
 * - NO languageCode field - use languageTag
 */
export interface SubtitleStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  /** v0.26.0 uses getLanguageTag(), NOT languageCode */
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
  manifestUrl: string;
}

export interface MetaInfo {
  title: string;
  content: string;
  urls: string[];
  urlTexts: string[];
}

export type StreamType =
  | 'VIDEO_STREAM'
  | 'AUDIO_STREAM'
  | 'LIVE_STREAM'
  | 'AUDIO_LIVE_STREAM'
  | 'POST_LIVE_STREAM'
  | 'POST_LIVE_AUDIO_STREAM'
  | 'NONE';

/** ContentAvailability enum from StreamInfo.getContentAvailability() */
export type StreamAvailability =
  | 'PUBLIC'
  | 'UNLISTED'
  | 'PRIVATE'
  | 'PREMIUM_ONLY'
  | 'SUBSCRIBER_ONLY'
  | 'MEMBERS_ONLY'
  | 'UNAVAILABLE';

// ─────────────────────────────────────────────
// InfoItem union (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

export interface StreamInfoItem {
  type: 'stream';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  thumbnails: NativeImage[];
  duration: number;
  viewCount: number;
  textualUploadDate: string;
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
}

export interface PlaylistInfoItem {
  type: 'playlist';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  thumbnails: NativeImage[];
  streamCount: number;
  playlistType: string;
}

export interface ChannelInfoItem {
  type: 'channel';
  serviceId: number;
  url: string;
  name: string;
  thumbnails: NativeImage[];
  subscriberCount: number;
  /** Available in ChannelInfoItem */
  streamCount: number;
  isVerified: boolean;
  description: string;
}

export type InfoItem = StreamInfoItem | PlaylistInfoItem | ChannelInfoItem;

// ─────────────────────────────────────────────
// Full StreamInfo (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * StreamInfo fields from Kotlin streamInfoToMap():
 * - Description.content mapped to both description and descriptionHtml
 * - getContentAvailability().name mapped to availability
 * - NO isUpcoming field in v0.26.0 Kotlin mapper
 */
export interface StreamInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  title: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  uploaderVerified: boolean;
  uploaderSubscriberCount: number;
  duration: number;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  description: string;
  /** Same as description (from Description.content) */
  descriptionHtml: string;
  uploadDate: string;
  textualUploadDate: string;
  thumbnails: NativeImage[];
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
  /** From getContentAvailability() */
  availability: StreamAvailability;
  ageLimit: number;
  tags: string[];
  category: string;
  audioStreams: AudioStream[];
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
  dashMpdUrl: string;
  hlsUrl: string;
  subtitles: SubtitleStream[];
  relatedItems: InfoItem[];
  metaInfo: MetaInfo[];
}

// ─────────────────────────────────────────────
// Comments (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * CommentsInfoItem fields:
 * - getReplies() returns Page? (nullable)
 * - hasCreatorReply() method
 */
export interface CommentItem {
  authorName: string;
  authorUrl: string;
  authorAvatars: NativeImage[];
  authorVerified: boolean;
  commentId: string;
  commentText: string;
  commentHtml: string;
  publishedTime: string;
  publishedTimestamp: number;
  likeCount: number;
  textualLikeCount: string;
  replyCount: number;
  /** From getReplies()?.getUrl() ?: "" */
  repliesPageUrl: string;
  hasReplies: boolean;
  isPinned: boolean;
  isHearted: boolean;
  isChannelOwner: boolean;
  hasCreatorReply: boolean;
  streamPosition: number;
}

export interface CommentsPage {
  success: boolean;
  disabled: boolean;
  commentsCount: number;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface CommentsMorePage {
  success: boolean;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface CommentRepliesPage {
  success: boolean;
  replies: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Search (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

export type SearchFilter = string;

export interface SearchPage {
  success: boolean;
  query: string;
  suggestion: string;
  isCorrectedSearch: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface SearchMorePage {
  success: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface SearchFiltersResult {
  serviceId: number;
  serviceName: string;
  availableFilters: string[];
}

// ─────────────────────────────────────────────
// Playlist (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * PlaylistInfo fields:
 * - NO viewCount field in v0.26.0 (removed from API)
 * - Description.content mapped to description
 */
export interface PlaylistInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  description: string;
  thumbnails: NativeImage[];
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  streamCount: number;
  playlistType: string;
  nextPage: NativePage;
  hasNextPage: boolean;
  items: InfoItem[];
  errors: string[];
}

export interface PlaylistItemsPage {
  success: boolean;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Channel (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * ChannelInfo fields:
 * - NO viewCount field in v0.26.0
 * - NO streamCount field in v0.26.0  
 * - NO nextPage field (ChannelInfo extends Info, not ListInfo)
 * - description is String (not Description object)
 */
export interface ChannelInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  /** Plain String, not Description object */
  description: string;
  avatars: NativeImage[];
  banners: NativeImage[];
  feedUrl: string;
  subscriberCount: number;
  isVerified: boolean;
  tabs: ChannelTab[];
  errors: string[];
}

export interface ChannelTab {
  name: string;
  contentFilters: string[];
  url: string;
}

export interface ChannelTabsResult {
  success: boolean;
  channelName: string;
  tabs: ChannelTab[];
}

export interface ChannelTabItemsPage {
  success: boolean;
  tabName: string;
  tabFilter: string;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/**
 * FeedInfo fields:
 * - NO pagination support in v0.26.0 (getMoreItems does not exist)
 * - Single page only
 */
export interface ChannelFeedResult {
  success: boolean;
  name: string;
  items: InfoItem[];
  errors: string[];
  /** Always false - FeedInfo has no pagination */
  hasNextPage: boolean;
  nextPage: NativePage;
}

// ─────────────────────────────────────────────
// Kiosk (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

export type KioskId = string;

export interface KioskEntry {
  id: string;
  name: string;
  url?: string;
  available: boolean;
  error?: string;
}

export interface KioskListResult {
  success: boolean;
  serviceId: number;
  defaultKioskId: string;
  kiosks: KioskEntry[];
}

export interface KioskPage {
  success: boolean;
  kioskId: string;
  name: string;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// URL Utilities (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

export interface ResolvedUrl {
  type: 'stream' | 'channel' | 'playlist';
  id: string;
  url: string;
  serviceId: number;
  serviceName: string;
}

export interface CanHandleResult {
  canHandle: boolean;
  linkType?: string;
  serviceId: number;
  serviceName?: string;
  url: string;
}

export interface ExtractedId {
  id: string;
  type: 'stream' | 'channel' | 'playlist';
  url: string;
  serviceId: number;
}

// ─────────────────────────────────────────────
// Misc (aligned with Kotlin v0.26.0)
// ─────────────────────────────────────────────

/**
 * ServiceInfo with v0.26.0 changes:
 * - getMediaCapabilities() returns Set<MediaCapability> (not List)
 */
export interface ServiceInfo {
  id: number;
  name: string;
  baseUrl: string;
  mediaCapabilities: string[];
}

export interface PingResult {
  alive: boolean;
  version: string;
  timestamp: number;
}

export interface StreamUrlResult {
  success: boolean;
  url: string;
  format: string;
  title: string;
  duration: number;
  fallbackUrls: string[];
}

export interface AudioStreamsResult {
  success: boolean;
  title: string;
  audioStreams: AudioStream[];
}

export interface VideoStreamsResult {
  success: boolean;
  title: string;
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
}

export interface SubtitlesResult {
  success: boolean;
  title: string;
  subtitles: SubtitleStream[];
  availableLanguages: string[];
}

export interface VersionInfo {
  version: string;
  library: string;
  releaseNotes?: string;
}

// ═════════════════════════════════════════════════════════════════
// STREAM FUNCTIONS
// ═════════════════════════════════════════════════════════════════

export const getStreamInfo = (
  url: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfo(url, serviceId ?? null);

export const getStreamInfoById = (
  videoId: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfoById(videoId, serviceId ?? null);

export const getStreamUrl = (
  url: string,
  format: 'audio' | 'video' | 'dash' | 'hls' | 'best' = 'best',
  serviceId?: number
): Promise<StreamUrlResult> =>
  Native.getStreamUrl(url, format, serviceId ?? null);

export const getAudioStreams = (
  url: string,
  serviceId?: number
): Promise<AudioStreamsResult> =>
  Native.getAudioStreams(url, serviceId ?? null);

export const getVideoStreams = (
  url: string,
  serviceId?: number
): Promise<VideoStreamsResult> =>
  Native.getVideoStreams(url, serviceId ?? null);

export const getSubtitles = (
  url: string,
  languageTag?: string,
  serviceId?: number
): Promise<SubtitlesResult> =>
  Native.getSubtitles(url, languageTag ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// COMMENTS
// ═════════════════════════════════════════════════════════════════

export const getComments = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<CommentsPage | CommentsMorePage> =>
  Native.getComments(url, pageUrl ?? null, serviceId ?? null);

export const getCommentReplies = (
  commentsUrl: string,
  repliesPageUrl: string,
  serviceId?: number
): Promise<CommentRepliesPage> =>
  Native.getCommentReplies(commentsUrl, repliesPageUrl, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// SEARCH
// ═════════════════════════════════════════════════════════════════

export const search = (
  query: string,
  filter: string = 'all',
  pageUrl?: string,
  serviceId?: number
): Promise<SearchPage | SearchMorePage> => {
  if (!query?.trim()) {
    return Promise.reject(new Error('Search query cannot be empty'));
  }
  return Native.search(query.trim(), filter, pageUrl ?? null, serviceId ?? null);
};

export const getSearchSuggestions = (
  query: string,
  serviceId?: number
): Promise<string[]> =>
  Native.getSearchSuggestions(query, serviceId ?? null);

export const getSearchFilters = (
  serviceId?: number
): Promise<SearchFiltersResult> =>
  Native.getSearchFilters(serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// PLAYLIST
// ═════════════════════════════════════════════════════════════════

export const getPlaylistInfo = (
  url: string,
  serviceId?: number
): Promise<PlaylistInfo> =>
  Native.getPlaylistInfo(url, serviceId ?? null);

export const getPlaylistItems = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<PlaylistItemsPage> =>
  Native.getPlaylistItems(url, pageUrl ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// CHANNEL
// ═════════════════════════════════════════════════════════════════

export const getChannelInfo = (
  url: string,
  serviceId?: number
): Promise<ChannelInfo> =>
  Native.getChannelInfo(url, serviceId ?? null);

export const getChannelTabs = (
  url: string,
  serviceId?: number
): Promise<ChannelTabsResult> =>
  Native.getChannelTabs(url, serviceId ?? null);

export const getChannelTabItems = (
  url: string,
  tabFilter: string,
  pageUrl?: string,
  serviceId?: number
): Promise<ChannelTabItemsPage> =>
  Native.getChannelTabItems(url, tabFilter, pageUrl ?? null, serviceId ?? null);

/**
 * Get feed items for a channel
 * NOTE: FeedInfo has NO pagination in v0.26.0 - pageUrl parameter removed
 */
export const getChannelFeed = (
  url: string,
  serviceId?: number
): Promise<ChannelFeedResult> =>
  Native.getChannelFeed(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// KIOSK
// ═════════════════════════════════════════════════════════════════

export const getKioskList = (
  serviceId?: number
): Promise<KioskListResult> =>
  Native.getKioskList(serviceId ?? null);

export const getKioskInfo = (
  kioskId: string,
  pageUrl?: string,
  serviceId?: number
): Promise<KioskPage> =>
  Native.getKioskInfo(kioskId, pageUrl ?? null, serviceId ?? null);

export const getTrending = (serviceId?: number): Promise<KioskPage> =>
  Native.getTrending(serviceId ?? null);

export const getMostPopular = (serviceId?: number): Promise<KioskPage> =>
  Native.getMostPopular(serviceId ?? null);

/**
 * Get YouTube kiosk by type.
 * 
 * UPDATED for NewPipeExtractor v0.26.0:
 * - Uses lowercase underscore IDs: 'trending_music', 'trending_movies_and_shows', 'live', etc.
 * - Supports both friendly names ('Trending Music') and actual IDs ('trending_music')
 * - Only 'trending_music' and 'trending_movies_and_shows' are working in v0.26.0
 * - 'Trending', 'live', 'trending_gaming', 'trending_podcasts_episodes' are broken (null pointer exceptions)
 * 
 * @param kioskType - Kiosk type or ID (case-insensitive, spaces/underscores/hyphens normalized)
 * @param serviceId - Service ID (default: 0 for YouTube)
 */
export const getYouTubeKiosk = (
  kioskType: 
    | 'LIVE' 
    | 'MUSIC' 
    | 'GAMING' 
    | 'MOVIES' 
    | 'TRENDING'
    | 'trending_music'
    | 'trending_movies_and_shows'
    | 'trending_gaming'
    | 'trending_podcasts_episodes'
    | 'live'
    | 'Trending',
  serviceId: number = 0
): Promise<KioskPage> =>
  Native.getYouTubeKiosk(kioskType, serviceId);

// ═════════════════════════════════════════════════════════════════
// URL UTILITIES
// ═════════════════════════════════════════════════════════════════

export const resolveUrl = (
  url: string,
  serviceId?: number
): Promise<ResolvedUrl> =>
  Native.resolveUrl(url, serviceId ?? null);

export const canHandleUrl = (
  url: string,
  serviceId?: number
): Promise<CanHandleResult> =>
  Native.canHandleUrl(url, serviceId ?? null);

export const extractIdFromUrl = (
  url: string,
  serviceId?: number
): Promise<ExtractedId> =>
  Native.extractIdFromUrl(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// MODULE PROPERTIES
// ═════════════════════════════════════════════════════════════════

export const version: string = Native.version;
export const initialized: boolean = Native.initialized;
export const services: ServiceInfo[] = Native.services;

// ═════════════════════════════════════════════════════════════════
// UTILITY FUNCTIONS
// ═════════════════════════════════════════════════════════════════

export const ping = (): Promise<PingResult> =>
  Native.ping();

export const emergencyReset = (): Promise<{ success: boolean; message: string }> =>
  Native.emergencyReset();

export const getVersion = (): Promise<VersionInfo> =>
  Native.getVersion();

// ═════════════════════════════════════════════════════════════════
// DEFAULT EXPORT
// ═════════════════════════════════════════════════════════════════

const MavinEngine = {
  version,
  initialized,
  services,
  
  getStreamInfo,
  getStreamInfoById,
  getStreamUrl,
  getAudioStreams,
  getVideoStreams,
  getSubtitles,
  
  getComments,
  getCommentReplies,
  
  search,
  getSearchSuggestions,
  getSearchFilters,
  
  getPlaylistInfo,
  getPlaylistItems,
  
  getChannelInfo,
  getChannelTabs,
  getChannelTabItems,
  getChannelFeed,
  
  getKioskList,
  getKioskInfo,
  getTrending,
  getMostPopular,
  getYouTubeKiosk,
  
  resolveUrl,
  canHandleUrl,
  extractIdFromUrl,
  
  ping,
  emergencyReset,
  getVersion,
};

export default MavinEngine;