/**
 * MavinEngine Native Module Wrapper
 *
 * Single source of truth JS/TS bridge.
 * Every function maps 1-to-1 to an AsyncFunction in MavinEngineModule.kt.
 *
 * Kotlin module name:  "MavinEngine"
 * Extractor version:   NewPipeExtractor v0.26.0
 * Architecture:        v10.0.0 — official Downloader pattern + CookieJar consent
 *
 * ── v10.0.0 changes (MavinEngineModule.kt) ──────────────────────────────────
 *
 * [A] MavinDownloader rewritten to match the official TeamNewPipe/NewPipe
 *     DownloaderImpl pattern: clean pass-through, no manual cookie injection.
 *     execute() forwards NewPipe's request headers as-is and lets the extractor
 *     classes populate YouTube-specific headers internally.
 *
 * [B] SOCS consent cookie is now seeded into an OkHttp SimpleCookieJar via
 *     YoutubeParsingHelper.generateConsentCookie() (static, no-network, no-throw).
 *     OkHttp attaches it automatically to every youtube.com/google.com request.
 *     The old hard-coded SOCS token string and manual addHeader("Cookie") injection
 *     inside execute() have been removed.
 *
 * [C] fetchAndCacheVisitorData() correctly calls getYouTubeHeaders() on a
 *     background thread (after init), not inside execute(). No recursion risk.
 *
 * [D] POST Content-Type default corrected from "application/x-www-form-urlencoded"
 *     to "application/json" — what InnerTube actually expects. The extractor's
 *     Content-Type header is forwarded as-is when present.
 *
 * ── v9.1 changes (retained) ─────────────────────────────────────────────────
 *
 * [8]  YoutubeParsingHelper.setConsentAccepted(true) called after NewPipe.init().
 * [9]  Real visitorData via YoutubeParsingHelper.getVisitorDataFromInnertube()
 *      using InnertubeClientRequestInfo.ofWebClient().
 * [10] WEB client no longer used for stream extraction (SABR-only player fix).
 * [11] Service.getMediaCapabilities() returns Set not List (breaking change handled).
 * [12] No getYouTubeHeaders() inside execute() (infinite recursion guard — now
 *      structurally impossible because the CookieJar pattern makes it unnecessary).
 *
 * ── v9.0 changes (retained) ─────────────────────────────────────────────────
 *
 * [1]  Long → Double at every bridge map boundary.
 * [2]  Int fields confirmed NOT needing .toDouble().
 * [3]  StreamInfo: startPosition, host, privacy, licence, languageInfo,
 *      subChannel*, streamSegments, previewFrames, supportInfo, errors.
 * [4]  ChannelInfo: tags, donationLinks, parentChannel*.
 * [5]  PlaylistInfo: banners, subChannel*.
 * [6]  getSearchSuggestions returns { suggestions: string[] } (Map root required).
 * [7]  StreamSegment and Frameset interfaces.
 *
 * Service IDs (NewPipe standard):
 *   0 = YouTube
 *   1 = SoundCloud
 *   2 = media.ccc.de
 *   3 = PeerTube
 *   4 = Bandcamp
 */

import { requireNativeModule } from 'expo-modules-core';

// ─────────────────────────────────────────────
// Native Module
// ─────────────────────────────────────────────

const Native = requireNativeModule('MavinEngine');

if (!Native) {
  console.error('[MavinEngine] CRITICAL: native module not loaded.');
}

// ─────────────────────────────────────────────
// Shared sub-types
// ─────────────────────────────────────────────

export interface NativeImage {
  url: string;
  width: number;
  height: number;
  resolutionLevel: 'UNKNOWN' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
}

/**
 * Pagination cursor returned by the Kotlin layer.
 * When there is no next page this is an empty object {}.
 * Always use hasNextPage to check — never inspect nextPage.url directly.
 */
export interface NativePage {
  url: string;
  ids: string[];
  cookies: Record<string, string>;
}

// ─────────────────────────────────────────────
// Stream types
// ─────────────────────────────────────────────

/**
 * AudioStream — v0.26.0 confirmed fields.
 * getBitrate() returns Int. Track fields are @Nullable — normalised to "".
 */
export interface AudioStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  bitrate: number;
  audioTrackId: string;
  audioTrackName: string;
  /** BCP-47 language tag, e.g. "en-US", or empty string */
  audioLocale: string;
  /** AudioTrackType enum name, e.g. "ORIGINAL", or empty string */
  audioTrackType: string;
  manifestUrl: string;
}

/**
 * VideoStream — v0.26.0 confirmed fields.
 * getWidth/Height/Fps/Bitrate return Int.
 */
export interface VideoStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  width: number;
  height: number;
  fps: number;
  bitrate: number;
  quality: string;
  manifestUrl: string;
}

/**
 * SubtitlesStream — v0.26.0 confirmed fields.
 * getLanguageTag() returns BCP-47 tag. displayLanguageName is @Nullable.
 */
export interface SubtitleStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
  manifestUrl: string;
}

/**
 * StreamSegment — v0.26.0 confirmed fields from StreamSegment javadoc.
 * getStartTimeSeconds() returns int (NOT Long — confirmed javadoc).
 * channelName, url, previewUrl are @Nullable — normalised to "".
 */
export interface StreamSegment {
  title: string;
  /** Seconds from start. int in Kotlin, JS number here. */
  startTimeSeconds: number;
  /** @Nullable — empty string if not provided */
  channelName: string;
  /** @Nullable — direct URL to this segment, empty string if not provided */
  url: string;
  /** @Nullable — thumbnail URL for this segment, empty string if not provided */
  previewUrl: string;
}

/**
 * Frameset — v0.26.0 confirmed fields from Frameset javadoc.
 * Used by StreamInfo.getPreviewFrames() for storyboard/sprite-sheet previews.
 */
export interface Frameset {
  /** Array of sprite-sheet image URLs */
  urls: string[];
  frameWidth: number;
  frameHeight: number;
  totalCount: number;
  /** Duration of each frame in milliseconds */
  durationPerFrame: number;
  framesPerPageX: number;
  framesPerPageY: number;
}

export interface MetaInfo {
  title: string;
  content: string;
  urls: string[];
  urlTexts: string[];
}

export type StreamType =
  | 'VIDEO_STREAM'
  | 'AUDIO_STREAM'
  | 'LIVE_STREAM'
  | 'AUDIO_LIVE_STREAM'
  | 'POST_LIVE_STREAM'
  | 'POST_LIVE_AUDIO_STREAM'
  | 'NONE';

export type StreamAvailability =
  | 'PUBLIC'
  | 'UNLISTED'
  | 'PRIVATE'
  | 'PREMIUM_ONLY'
  | 'SUBSCRIBER_ONLY'
  | 'MEMBERS_ONLY'
  | 'UNAVAILABLE';

/**
 * StreamExtractor.Privacy enum — v0.26.0.
 * Maps to the Kotlin Privacy.name string returned in the bridge map.
 */
export type StreamPrivacy =
  | 'PUBLIC'
  | 'UNLISTED'
  | 'PRIVATE'
  | 'INTERNAL'
  | 'OTHER';

// ─────────────────────────────────────────────
// InfoItem union
// ─────────────────────────────────────────────

/**
 * duration and viewCount are Long in the NewPipe extractor, coerced to >= 0
 * then converted to Double in Kotlin. They arrive here as JS number.
 */
export interface StreamInfoItem {
  type: 'stream';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  thumbnails: NativeImage[];
  /** Seconds. 0 if unknown. (Long→Double in Kotlin) */
  duration: number;
  /** 0 if unknown. (Long→Double in Kotlin) */
  viewCount: number;
  textualUploadDate: string;
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
}

/** streamCount is Long in extractor, coerced to >= 0 then Double. */
export interface PlaylistInfoItem {
  type: 'playlist';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  thumbnails: NativeImage[];
  /** 0 if unknown. (Long→Double in Kotlin) */
  streamCount: number;
  playlistType: string;
}

/** subscriberCount and streamCount are Long in extractor, coerced then Double. */
export interface ChannelInfoItem {
  type: 'channel';
  serviceId: number;
  url: string;
  name: string;
  thumbnails: NativeImage[];
  /** 0 if unknown. (Long→Double in Kotlin) */
  subscriberCount: number;
  /** 0 if unknown. (Long→Double in Kotlin) */
  streamCount: number;
  isVerified: boolean;
  description: string;
}

export type InfoItem = StreamInfoItem | PlaylistInfoItem | ChannelInfoItem;

// ─────────────────────────────────────────────
// Full StreamInfo
// ─────────────────────────────────────────────

/**
 * Full stream info returned by getStreamInfo() / getStreamInfoById().
 * All fields confirmed against v0.26.0 javadoc.
 * Long fields in Kotlin are coerced to Double and arrive here as JS number.
 *
 * v10.0.0 note: stream URLs are now extracted using the YouTube Android/iOS
 * client (not WEB) — fix [10] / [A]. This resolves SABR-only player responses
 * that previously caused empty audioStreams/videoStreams arrays.
 */
export interface StreamInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  title: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  uploaderVerified: boolean;
  /** (Long→Double in Kotlin) */
  uploaderSubscriberCount: number;
  /** Seconds. (Long→Double) */
  duration: number;
  /** (Long→Double) */
  viewCount: number;
  /** -1 coerced to 0. (Long→Double) */
  likeCount: number;
  /** -1 coerced to 0. (Long→Double) */
  dislikeCount: number;
  description: string;
  uploadDate: string;
  textualUploadDate: string;
  thumbnails: NativeImage[];
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
  availability: StreamAvailability;
  /** int in Kotlin — no Double conversion needed */
  ageLimit: number;
  tags: string[];
  category: string;
  /**
   * Playback start position in seconds. (Long→Double)
   * Typically 0. Non-zero when the URL includes a timestamp.
   */
  startPosition: number;
  /** PeerTube host, empty for YouTube */
  host: string;
  /** StreamExtractor.Privacy enum name */
  privacy: StreamPrivacy;
  /** Content licence string, empty if not provided */
  licence: string;
  /**
   * BCP-47 language tag of the stream's language, e.g. "en-US".
   * Empty string if not set.
   */
  languageInfo: string;
  /** Sub-channel name (e.g. YouTube topic channel), empty if not provided */
  subChannelName: string;
  /** Sub-channel URL, empty if not provided */
  subChannelUrl: string;
  subChannelAvatars: NativeImage[];
  /** Support / crowdfunding info string, empty if not provided */
  supportInfo: string;
  audioStreams: AudioStream[];
  videoStreams: VideoStream[];
  /**
   * DASH adaptive video-only streams (no embedded audio).
   * These are the HD streams (720p, 1080p, etc.) on YouTube.
   * Pair with the highest-bitrate audioStream for full HD playback.
   */
  videoOnlyStreams: VideoStream[];
  dashMpdUrl: string;
  hlsUrl: string;
  subtitles: SubtitleStream[];
  relatedItems: InfoItem[];
  /**
   * Chapter/segment markers within the stream.
   * StreamSegment.startTimeSeconds is int in Kotlin.
   */
  streamSegments: StreamSegment[];
  /** Storyboard/sprite-sheet preview frames for seek thumbnails. */
  previewFrames: Frameset[];
  metaInfo: MetaInfo[];
  /** Extraction errors (non-fatal). Usually empty. */
  errors: string[];
}

// ─────────────────────────────────────────────
// Comments
// ─────────────────────────────────────────────

export interface CommentItem {
  authorName: string;
  authorUrl: string;
  authorAvatars: NativeImage[];
  authorVerified: boolean;
  commentId: string;
  commentText: string;
  publishedTime: string;
  /** Epoch seconds as Double→number. 0 if unavailable. */
  publishedTimestamp: number;
  /**
   * int in Kotlin (NOT Long — confirmed v0.26.0 javadoc).
   * CommentsInfoItem.NO_LIKE_COUNT coerced to 0.
   */
  likeCount: number;
  textualLikeCount: string;
  /** int in Kotlin. UNKNOWN_REPLY_COUNT when not available. */
  replyCount: number;
  repliesPageUrl: string;
  hasReplies: boolean;
  isPinned: boolean;
  isHearted: boolean;
  isChannelOwner: boolean;
  hasCreatorReply: boolean;
  /** int in Kotlin. NO_STREAM_POSITION when not available. */
  streamPosition: number;
}

export interface CommentsPage {
  success: boolean;
  disabled: boolean;
  /** int in Kotlin — CommentsInfo.getCommentsCount() */
  commentsCount: number;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface CommentsMorePage {
  success: boolean;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface CommentRepliesPage {
  success: boolean;
  replies: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Search
// ─────────────────────────────────────────────

/**
 * Valid content filter tokens for YouTube (NewPipe SearchQueryHandlerFactory).
 *
 * ''                → no filter — returns all content types
 * 'videos'          → video results only
 * 'channels'        → channel results only
 * 'playlists'       → playlist results only
 * 'music_songs'     → YouTube Music: songs
 * 'music_videos'    → YouTube Music: music videos
 * 'music_albums'    → YouTube Music: albums
 * 'music_playlists' → YouTube Music: playlists
 *
 * IMPORTANT: 'all' is NOT a valid NewPipe filter token.
 * Use '' (empty string) for unfiltered / all-types search.
 */
export type YouTubeSearchFilter =
  | ''
  | 'videos'
  | 'channels'
  | 'playlists'
  | 'music_songs'
  | 'music_videos'
  | 'music_albums'
  | 'music_playlists';

export type SearchFilter = YouTubeSearchFilter | string;

/** Returned by search() on first page (no pageUrl) */
export interface SearchPage {
  success: boolean;
  query: string;
  suggestion: string;
  isCorrectedSearch: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/** Returned by search() when a pageUrl is supplied */
export interface SearchMorePage {
  success: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/**
 * Returned by getSearchSuggestions().
 * The Kotlin layer wraps the List<String> in a Map so the bridge can serialise it.
 * Fix [6]: Map root required for expo-modules-core serialisation.
 */
export interface SearchSuggestionsResult {
  suggestions: string[];
}

export interface SearchFiltersResult {
  serviceId: number;
  serviceName: string;
  availableFilters: string[];
}

// ─────────────────────────────────────────────
// Playlist
// ─────────────────────────────────────────────

/**
 * Full playlist info — all fields confirmed against v0.26.0 javadoc.
 * Fix [5]: banners, subChannelName, subChannelUrl, subChannelAvatars added in v9.0.
 */
export interface PlaylistInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  description: string;
  thumbnails: NativeImage[];
  banners: NativeImage[];
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  subChannelName: string;
  subChannelUrl: string;
  subChannelAvatars: NativeImage[];
  /** (Long→Double) */
  streamCount: number;
  playlistType: string;
  nextPage: NativePage;
  hasNextPage: boolean;
  items: InfoItem[];
  errors: string[];
}

export interface PlaylistItemsPage {
  success: boolean;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Channel
// ─────────────────────────────────────────────

/**
 * Full channel info — all fields confirmed against v0.26.0 javadoc.
 * Fix [4]: tags, donationLinks, parentChannel* added in v9.0.
 */
export interface ChannelInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  description: string;
  avatars: NativeImage[];
  banners: NativeImage[];
  feedUrl: string;
  /** (Long→Double) */
  subscriberCount: number;
  isVerified: boolean;
  /** ChannelInfo.getTags() → List<String> in v0.26.0 */
  tags: string[];
  /** ChannelInfo.getDonationLinks() → String[] in v0.26.0, converted to string[] */
  donationLinks: string[];
  parentChannelName: string;
  parentChannelUrl: string;
  parentChannelAvatars: NativeImage[];
  tabs: ChannelTab[];
  errors: string[];
}

export interface ChannelTab {
  name: string;
  contentFilters: string[];
  url: string;
}

export interface ChannelTabItemsPage {
  success: boolean;
  tabName: string;
  tabFilter: string;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface ChannelFeedResult {
  success: boolean;
  name: string;
  items: InfoItem[];
  errors: string[];
}

// ─────────────────────────────────────────────
// Kiosk
// ─────────────────────────────────────────────

export interface KioskEntry {
  id: string;
  name: string;
  url?: string;
  available: boolean;
  error?: string;
}

export interface KioskListResult {
  success: boolean;
  serviceId: number;
  defaultKioskId: string;
  kiosks: KioskEntry[];
}

export interface KioskPage {
  success: boolean;
  kioskId: string;
  name?: string;
  items: InfoItem[];
  nextPage?: NativePage;
  hasNextPage?: boolean;
  errors?: string[];
  /** Only present when success === false */
  error?: string;
  /** Only present when success === false */
  message?: string;
}

// ─────────────────────────────────────────────
// Trending — 6-layer fallback
// ─────────────────────────────────────────────

export type TrendingSource =
  | 'youtube_music_charts'
  | 'innertube_browse'
  | `kiosk_${string}`
  | 'youtube_charts_html'
  | 'innertube_next_recommendations'
  | `search_${number}`
  | 'cache'
  | 'none';

export interface TrendingResult {
  success: boolean;
  source: TrendingSource;
  items: InfoItem[];
  totalAvailable: number;
  errors: string[];
  /** Only present when success === false */
  message?: string;
}

// ─────────────────────────────────────────────
// InnerTube config
// ─────────────────────────────────────────────

export interface InnerTubeConfig {
  apiKey: string;
  clientVersion: string;
  musicClientVersion: string;
  /** Cache age in milliseconds. (Long→Double in Kotlin) */
  cacheAge: number;
  isCached: boolean;
}

export interface InnerTubeRefreshResult {
  success: boolean;
  apiKey: string;
  clientVersion: string;
  musicClientVersion: string;
}

// ─────────────────────────────────────────────
// API key management
// ─────────────────────────────────────────────

export interface ApiKeyStatus {
  totalKeys: number;
  failedKeys: number;
  workingKeys: number;
  currentKeyIndex: number;
}

// ─────────────────────────────────────────────
// Trending cache
// ─────────────────────────────────────────────

export interface TrendingCacheStatus {
  hasCachedData: boolean;
  /** (Long→Double in Kotlin) */
  cacheAgeMs: number;
  /** (Long→Double in Kotlin) */
  ttlMs: number;
  isValid: boolean;
}

// ─────────────────────────────────────────────
// Visitor data
// ─────────────────────────────────────────────

/**
 * Status of the cached visitorData token.
 *
 * Fix [9] / [C]: Fetched via YoutubeParsingHelper.getVisitorDataFromInnertube()
 * on a background thread after init. YouTube rejects synthetic visitor IDs.
 * Token is prefetched at init and auto-refreshed every hour.
 *
 * v10.0.0: getYouTubeHeaders() is called inside fetchAndCacheVisitorData()
 * on a background thread — never inside execute() — so there is no recursion risk.
 */
export interface VisitorDataStatus {
  hasVisitorData: boolean;
  /** Cache age in milliseconds. (Long→Double in Kotlin) */
  cacheAgeMs: number;
  /** TTL in milliseconds (1 hour). (Long→Double in Kotlin) */
  ttlMs: number;
  isValid: boolean;
}

export interface VisitorDataRefreshResult {
  success: boolean;
  hasVisitorData: boolean;
}

// ─────────────────────────────────────────────
// URL utilities
// ─────────────────────────────────────────────

export interface ResolvedUrl {
  type: 'stream' | 'channel' | 'playlist' | 'none';
  id: string;
  url: string;
  serviceId: number;
  serviceName: string;
}

export interface CanHandleResult {
  canHandle: boolean;
  linkType: string;
  serviceId: number;
  serviceName: string;
  url: string;
}

export interface ExtractedId {
  id: string;
  type: string;
  url: string;
  serviceId: number;
}

// ─────────────────────────────────────────────
// Utility
// ─────────────────────────────────────────────

export interface PingResult {
  alive: boolean;
  version: string;
  /** (Long→Double in Kotlin) */
  timestamp: number;
}

export interface ResetResult {
  success: boolean;
  message: string;
}

export interface VersionInfo {
  version: string;
  library: string;
  architecture: string;
  notes: string[];
}

export interface ServiceInfo {
  id: number;
  name: string;
  baseUrl: string;
  /**
   * Fix [11]: getMediaCapabilities() returns Set not List in v0.26.0.
   * Handled in Kotlin's getServicesList() — arrives here as string[] regardless.
   */
  mediaCapabilities: string[];
}

// ═════════════════════════════════════════════════════════════════
// STREAMS
// ═════════════════════════════════════════════════════════════════

/**
 * Extract full stream info including all audio/video streams, metadata, etc.
 *
 * Fix [10] / [A]: Uses the YouTube Android/iOS client internally (not WEB client).
 * This resolves the SABR-only player response issue that caused empty stream arrays
 * with the WEB client in v0.26.0.
 */
export const getStreamInfo = (url: string, serviceId?: number): Promise<StreamInfo> =>
  Native.getStreamInfo(url, serviceId ?? null);

export const getStreamInfoById = (videoId: string, serviceId?: number): Promise<StreamInfo> =>
  Native.getStreamInfoById(videoId, serviceId ?? null);

/**
 * Get the single best stream URL for a given format.
 *
 * format notes:
 *   'audio'/'mp3'/'m4a'/'ogg'/'webm' → highest-bitrate audio-only stream
 *   'video'/'mp4'/'best'             → highest-resolution videoOnlyStream (DASH),
 *                                      falling back to muxed videoStream
 *   'dash'                           → dashMpdUrl
 *   'hls'                            → hlsUrl
 *
 * For full HD video+audio playback use getStreamInfo() directly and pair
 * videoOnlyStreams (DASH, no audio) with audioStreams in your player.
 */
export const getStreamUrl = (
  url: string,
  format?: 'audio' | 'video' | 'mp3' | 'm4a' | 'ogg' | 'mp4' | 'best' | 'dash' | 'hls',
  serviceId?: number
): Promise<{
  success: boolean;
  url: string;
  format: string;
  title: string;
  /** (Long→Double in Kotlin) */
  duration: number;
  fallbackUrls: string[];
}> =>
  Native.getStreamUrl(url, format ?? null, serviceId ?? null);

export const getAudioStreams = (
  url: string,
  serviceId?: number
): Promise<{ success: boolean; title: string; audioStreams: AudioStream[] }> =>
  Native.getAudioStreams(url, serviceId ?? null);

export const getVideoStreams = (
  url: string,
  serviceId?: number
): Promise<{
  success: boolean;
  title: string;
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
}> =>
  Native.getVideoStreams(url, serviceId ?? null);

export const getSubtitles = (
  url: string,
  language?: string,
  serviceId?: number
): Promise<{
  success: boolean;
  title: string;
  subtitles: SubtitleStream[];
  availableLanguages: string[];
}> =>
  Native.getSubtitles(url, language ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// COMMENTS
// ═════════════════════════════════════════════════════════════════

export const getComments = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<CommentsPage | CommentsMorePage> =>
  Native.getComments(url, pageUrl ?? null, serviceId ?? null);

export const getCommentReplies = (
  commentsUrl: string,
  repliesPageUrl: string,
  serviceId?: number
): Promise<CommentRepliesPage> =>
  Native.getCommentReplies(commentsUrl, repliesPageUrl, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// SEARCH
// ═════════════════════════════════════════════════════════════════

/**
 * Search for content on a service.
 *
 * filter: use '' (empty string, the default) for all content types.
 *   Per NewPipe API docs, an empty contentFilter list means no filter.
 *   'all' is NOT a valid NewPipe filter — always use '' for unfiltered results.
 *
 * Valid YouTube filters:
 *   'videos' | 'channels' | 'playlists' |
 *   'music_songs' | 'music_videos' | 'music_albums' | 'music_playlists'
 *
 * serviceId: omit or pass undefined for YouTube (0 = default).
 */
export const search = (
  query: string,
  filter: SearchFilter = '',
  pageUrl?: string,
  serviceId?: number
): Promise<SearchPage | SearchMorePage> => {
  if (!query?.trim()) {
    return Promise.reject(new Error('Search query cannot be empty'));
  }
  return Native.search(query.trim(), filter, pageUrl ?? null, serviceId ?? null);
};

/**
 * Get search suggestions for a partial query.
 *
 * Returns { suggestions: string[] }.
 * Fix [6]: The Kotlin layer wraps List<String> in a Map root for bridge serialisation.
 */
export const getSearchSuggestions = (
  query: string,
  serviceId?: number
): Promise<SearchSuggestionsResult> =>
  Native.getSearchSuggestions(query, serviceId ?? null);

export const getSearchFilters = (serviceId?: number): Promise<SearchFiltersResult> =>
  Native.getSearchFilters(serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// PLAYLIST
// ═════════════════════════════════════════════════════════════════

export const getPlaylistInfo = (url: string, serviceId?: number): Promise<PlaylistInfo> =>
  Native.getPlaylistInfo(url, serviceId ?? null);

export const getPlaylistItems = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<PlaylistItemsPage> =>
  Native.getPlaylistItems(url, pageUrl ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// CHANNEL
// ═════════════════════════════════════════════════════════════════

export const getChannelInfo = (url: string, serviceId?: number): Promise<ChannelInfo> =>
  Native.getChannelInfo(url, serviceId ?? null);

export const getChannelTabItems = (
  url: string,
  tabFilter: string,
  pageUrl?: string,
  serviceId?: number
): Promise<ChannelTabItemsPage> =>
  Native.getChannelTabItems(url, tabFilter, pageUrl ?? null, serviceId ?? null);

export const getChannelFeed = (url: string, serviceId?: number): Promise<ChannelFeedResult> =>
  Native.getChannelFeed(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// KIOSK
// ═════════════════════════════════════════════════════════════════

export const getKioskList = (serviceId?: number): Promise<KioskListResult> =>
  Native.getKioskList(serviceId ?? null);

/**
 * Fetch a specific kiosk by ID.
 *
 * Valid YouTube kiosk IDs in v0.26.0:
 *   "Live" | "trending_music" | "trending_gaming" |
 *   "trending_movies_and_shows" | "trending_podcasts_episodes"
 *
 * "Trending" (global feed) was removed by YouTube on 2025-07-21.
 * An invalid kioskId returns { success: false } rather than throwing.
 */
export const getKioskInfo = (
  kioskId: string,
  pageUrl?: string,
  serviceId?: number
): Promise<KioskPage> =>
  Native.getKioskInfo(kioskId, pageUrl ?? null, serviceId ?? null);

/** @deprecated Use getTrendingWithFallback() — YouTube Trending removed 2025-07-21 */
export const getTrending = (serviceId?: number): Promise<TrendingResult> =>
  Native.getTrending(serviceId ?? null);

/** @deprecated Use getTrendingWithFallback() — YouTube Trending removed 2025-07-21 */
export const getMostPopular = (serviceId?: number): Promise<TrendingResult> =>
  Native.getMostPopular(serviceId ?? null);

/** @deprecated Use getTrendingWithFallback() — YouTube Trending removed 2025-07-21 */
export const getYouTubeKiosk = (
  kioskType:
    | 'live' | 'Live'
    | 'trending' | 'Trending'
    | 'music' | 'trending_music'
    | 'gaming' | 'trending_gaming'
    | 'movies' | 'trending_movies' | 'trending_movies_and_shows'
    | 'podcasts' | 'trending_podcasts' | 'trending_podcasts_episodes',
  serviceId: number = 0
): Promise<KioskPage> =>
  Native.getYouTubeKiosk(kioskType, serviceId);

// ═════════════════════════════════════════════════════════════════
// TRENDING — 6-LAYER FALLBACK
// ═════════════════════════════════════════════════════════════════

/**
 * Fetch trending content with 6-layer fallback.
 * Recommended since YouTube removed the global Trending page (2025-07-21).
 *
 * Layer 1: YouTube Music Charts (FEmusic_charts)    — InnerTube WEB_REMIX client
 * Layer 2: InnerTube Browse (FEwhat_to_watch)       — homepage feed
 * Layer 3: NewPipe sub-kiosks                       — trending_music / trending_gaming / etc.
 * Layer 4: YouTube Charts HTML (charts.youtube.com) — HTML scrape
 * Layer 5: InnerTube Next API                       — recommendations seed
 * Layer 6: Search fallback                          — "trending music official video {year}"
 *
 * Results are cached for 5 minutes. Inspect result.source to see which layer succeeded.
 * result.success === false means all 6 layers failed; result.errors lists each failure.
 *
 * v10.0.0: Layers 1, 2, 4, 5 use the direct OkHttpClient (not MavinDownloader),
 * so they benefit from the CookieJar consent cookie automatically.
 */
export const getTrendingWithFallback = (
  category: 'music' | 'gaming' | 'movies' | 'podcast' | 'videos' | string = 'music',
  serviceId?: number
): Promise<TrendingResult> =>
  Native.getTrendingWithFallback(category, serviceId ?? 0);

// ═════════════════════════════════════════════════════════════════
// INNERTUBE CONFIG
// ═════════════════════════════════════════════════════════════════

export const getInnerTubeConfig = (): Promise<InnerTubeConfig> =>
  Native.getInnerTubeConfig();

export const refreshInnerTubeConfig = (): Promise<InnerTubeRefreshResult> =>
  Native.refreshInnerTubeConfig();

// ═════════════════════════════════════════════════════════════════
// VISITOR DATA
// ═════════════════════════════════════════════════════════════════

/**
 * Refresh the cached visitorData token.
 *
 * Fix [9] / [C]: Calls YoutubeParsingHelper.getVisitorDataFromInnertube() on
 * a background thread using InnertubeClientRequestInfo.ofWebClient().
 *
 * The token is prefetched at module init and auto-refreshed every hour.
 * Call manually only if you see "Could not get visitorData" errors or
 * getVisitorDataStatus() reports isValid === false.
 *
 * v10.0.0: getYouTubeHeaders() (called internally during fetch) runs on the
 * background thread, not inside execute() — zero recursion risk.
 */
export const refreshVisitorData = (): Promise<VisitorDataRefreshResult> =>
  Native.refreshVisitorData();

/**
 * Check the current status of the cached visitorData token.
 * Useful for diagnosing stream extraction or search failures.
 */
export const getVisitorDataStatus = (): Promise<VisitorDataStatus> =>
  Native.getVisitorDataStatus();

// ═════════════════════════════════════════════════════════════════
// KEY MANAGEMENT
// ═════════════════════════════════════════════════════════════════

export const getApiKeyStatus = (): Promise<ApiKeyStatus> =>
  Native.getApiKeyStatus();

export const resetFailedKeys = (): Promise<{ success: boolean }> =>
  Native.resetFailedKeys();

// ═════════════════════════════════════════════════════════════════
// TRENDING CACHE
// ═════════════════════════════════════════════════════════════════

export const clearTrendingCache = (): Promise<{ success: boolean }> =>
  Native.clearTrendingCache();

export const getTrendingCacheStatus = (): Promise<TrendingCacheStatus> =>
  Native.getTrendingCacheStatus();

// ═════════════════════════════════════════════════════════════════
// URL UTILITIES
// ═════════════════════════════════════════════════════════════════

export const resolveUrl = (url: string, serviceId?: number): Promise<ResolvedUrl> =>
  Native.resolveUrl(url, serviceId ?? null);

export const canHandleUrl = (url: string, serviceId?: number): Promise<CanHandleResult> =>
  Native.canHandleUrl(url, serviceId ?? null);

export const extractIdFromUrl = (url: string, serviceId?: number): Promise<ExtractedId> =>
  Native.extractIdFromUrl(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// MODULE PROPERTIES
// ═════════════════════════════════════════════════════════════════

export const version: string      = Native.version;
export const initialized: boolean = Native.initialized;
export const services: ServiceInfo[] = Native.services;

// ═════════════════════════════════════════════════════════════════
// UTILITY
// ═════════════════════════════════════════════════════════════════

export const ping = (): Promise<PingResult> =>
  Native.ping();

export const emergencyReset = (): Promise<ResetResult> =>
  Native.emergencyReset();

export const getVersion = (): Promise<VersionInfo> =>
  Native.getVersion();

// ═════════════════════════════════════════════════════════════════
// DEFAULT EXPORT
// ═════════════════════════════════════════════════════════════════

const MavinEngine = {
  // Properties
  version,
  initialized,
  services,

  // Streams
  getStreamInfo,
  getStreamInfoById,
  getStreamUrl,
  getAudioStreams,
  getVideoStreams,
  getSubtitles,

  // Comments
  getComments,
  getCommentReplies,

  // Search
  search,
  getSearchSuggestions,
  getSearchFilters,

  // Playlist
  getPlaylistInfo,
  getPlaylistItems,

  // Channel
  getChannelInfo,
  getChannelTabItems,
  getChannelFeed,

  // Kiosk
  getKioskList,
  getKioskInfo,
  /** @deprecated Use getTrendingWithFallback() */
  getTrending,
  /** @deprecated Use getTrendingWithFallback() */
  getMostPopular,
  /** @deprecated Use getTrendingWithFallback() */
  getYouTubeKiosk,

  // Trending
  getTrendingWithFallback,

  // InnerTube config
  getInnerTubeConfig,
  refreshInnerTubeConfig,

  // Visitor data — fix [9] / [C]
  refreshVisitorData,
  getVisitorDataStatus,

  // Key management
  getApiKeyStatus,
  resetFailedKeys,

  // Trending cache
  clearTrendingCache,
  getTrendingCacheStatus,

  // URL utilities
  resolveUrl,
  canHandleUrl,
  extractIdFromUrl,

  // Utility
  ping,
  emergencyReset,
  getVersion,
};

export default MavinEngine;