/**
 * MavinEngine Native Module Wrapper
 *
 * Single source of truth JS/TS bridge.
 * Every function maps 1-to-1 to an AsyncFunction in MavinEngineModule.kt.
 *
 * Kotlin module name:  "MavinEngine"
 * Extractor version:   NewPipeExtractor v0.26.0
 * Architecture:        v8.1 — post-July-2025, YouTube Charts-first, 6-layer fallback
 *
 * Service IDs (NewPipe standard):
 *   0 = YouTube
 *   1 = SoundCloud
 *   2 = media.ccc.de
 *   3 = PeerTube
 *   4 = Bandcamp
 *
 * Deep linking:
 *   canHandleUrl → resolveUrl / extractIdFromUrl → getStreamInfo / getChannelInfo / getPlaylistInfo
 */

import { requireNativeModule } from 'expo-modules-core';

// ─────────────────────────────────────────────
// Native Module
// ─────────────────────────────────────────────

const Native = requireNativeModule('MavinEngine');

if (!Native) {
  console.error('[MavinEngine] CRITICAL: native module not loaded.');
}

// ─────────────────────────────────────────────
// Shared sub-types
// ─────────────────────────────────────────────

export interface NativeImage {
  url: string;
  width: number;
  height: number;
  resolutionLevel: 'UNKNOWN' | 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
}

/**
 * Pagination cursor returned by the Kotlin layer.
 * When there is no next page this is an empty object {}.
 * Always use hasNextPage to check — never inspect nextPage.url directly.
 *
 * Page is a Java class in NewPipe. expo-modules-core deserialises
 * getUrl(), getIds(), getCookies() as plain object fields.
 */
export interface NativePage {
  url: string;
  ids: string[];
  cookies: Record<string, string>;
}

// ─────────────────────────────────────────────
// Stream types
// ─────────────────────────────────────────────

/**
 * AudioStream — v0.26.0 confirmed fields.
 * getBitrate() returns int. getAudioTrackId/Name/Locale/Type are all @Nullable
 * in the extractor — the Kotlin layer normalises nulls to empty strings.
 */
export interface AudioStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  bitrate: number;
  audioTrackId: string;
  audioTrackName: string;
  /** BCP-47 language tag, e.g. "en-US", or empty string */
  audioLocale: string;
  /** AudioTrackType enum name, e.g. "ORIGINAL", or empty string */
  audioTrackType: string;
  manifestUrl: string;
}

/**
 * VideoStream — v0.26.0 confirmed fields.
 * getWidth/Height/Fps/Bitrate return int. getQuality/getCodec return String.
 * The deprecated public fields resolution and isVideoOnly are not exposed here —
 * use getResolution() / isVideoOnly() via the stream objects directly if needed.
 */
export interface VideoStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  codec: string;
  width: number;
  height: number;
  fps: number;
  bitrate: number;
  quality: string;
  manifestUrl: string;
}

/**
 * SubtitlesStream — v0.26.0 confirmed fields.
 * getLanguageTag() returns BCP-47 tag. displayLanguageName is @Nullable
 * — Kotlin normalises to empty string.
 */
export interface SubtitleStream {
  url: string;
  isUrl: boolean;
  deliveryMethod: string;
  format: string;
  /** BCP-47 language tag from getLanguageTag(), e.g. "en", "fr-CA" */
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
  manifestUrl: string;
}

/**
 * MetaInfo — contextual info panel (e.g. COVID health notices, fact checks).
 * content is from Description.content — never null in v0.26.0
 * (Kotlin uses safe-call as defensive measure for cross-service implementations).
 */
export interface MetaInfo {
  title: string;
  content: string;
  urls: string[];
  urlTexts: string[];
}

export type StreamType =
  | 'VIDEO_STREAM'
  | 'AUDIO_STREAM'
  | 'LIVE_STREAM'
  | 'AUDIO_LIVE_STREAM'
  | 'POST_LIVE_STREAM'
  | 'POST_LIVE_AUDIO_STREAM'
  | 'NONE';

/** From StreamInfo.getContentAvailability().name */
export type StreamAvailability =
  | 'PUBLIC'
  | 'UNLISTED'
  | 'PRIVATE'
  | 'PREMIUM_ONLY'
  | 'SUBSCRIBER_ONLY'
  | 'MEMBERS_ONLY'
  | 'UNAVAILABLE';

// ─────────────────────────────────────────────
// InfoItem union
// ─────────────────────────────────────────────

/**
 * duration and viewCount are Long in Kotlin, coerced to >= 0.
 * They use -1 as the "unknown" sentinel in the extractor; the Kotlin layer
 * normalises them to 0 via coerceAtLeast(0L).
 */
export interface StreamInfoItem {
  type: 'stream';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderVerified: boolean;
  thumbnails: NativeImage[];
  duration: number;
  viewCount: number;
  textualUploadDate: string;
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
}

/**
 * streamCount is Long, coerced to >= 0 via coerceAtLeast(0L).
 * playlistType is the PlaylistType enum name, defaulting to "NORMAL".
 */
export interface PlaylistInfoItem {
  type: 'playlist';
  serviceId: number;
  url: string;
  name: string;
  uploaderName: string;
  uploaderUrl: string;
  thumbnails: NativeImage[];
  streamCount: number;
  playlistType: string;
}

/**
 * subscriberCount and streamCount are Long, coerced to >= 0.
 * description is a plain String from ChannelInfoItem — not a Description object.
 */
export interface ChannelInfoItem {
  type: 'channel';
  serviceId: number;
  url: string;
  name: string;
  thumbnails: NativeImage[];
  subscriberCount: number;
  streamCount: number;
  isVerified: boolean;
  description: string;
}

export type InfoItem = StreamInfoItem | PlaylistInfoItem | ChannelInfoItem;

// ─────────────────────────────────────────────
// Full StreamInfo
// ─────────────────────────────────────────────

/**
 * Exact shape of what streamInfoToMap() returns in Kotlin.
 *
 * Key points:
 * - description comes from Description.content (@Nonnull in v0.26.0)
 * - NO descriptionHtml field — the Kotlin mapper does not produce one
 * - uploadDate is an ISO-8601 string from DateWrapper.offsetDateTime().toString(),
 *   or "" if the stream has no date (e.g. live streams)
 * - uploaderSubscriberCount uses -1 sentinel normalised to 0
 * - availability comes from getContentAvailability().name
 */
export interface StreamInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  title: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  uploaderVerified: boolean;
  uploaderSubscriberCount: number;
  duration: number;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  /** From Description.content — plain text, never HTML */
  description: string;
  /** ISO-8601 string, or "" for live streams / when unavailable */
  uploadDate: string;
  textualUploadDate: string;
  thumbnails: NativeImage[];
  streamType: StreamType;
  isLive: boolean;
  isShortFormContent: boolean;
  availability: StreamAvailability;
  ageLimit: number;
  tags: string[];
  category: string;
  audioStreams: AudioStream[];
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
  dashMpdUrl: string;
  hlsUrl: string;
  subtitles: SubtitleStream[];
  /** First 20 related items */
  relatedItems: InfoItem[];
  metaInfo: MetaInfo[];
}

// ─────────────────────────────────────────────
// Comments
// ─────────────────────────────────────────────

/**
 * Exact shape of commentItemToMap() in Kotlin.
 *
 * Key points:
 * - commentText comes from CommentsInfoItem.commentText.content
 *   (@Nonnull Description confirmed from v0.26.0 Javadoc)
 * - NO commentHtml field — the Kotlin mapper does not produce one
 * - publishedTimestamp is epoch seconds (Long), or 0 if upload date is null
 * - likeCount uses NO_LIKE_COUNT sentinel, normalised to 0 via coerceAtLeast
 * - repliesPageUrl comes from getReplies()?.url — empty string when no replies
 * - streamPosition is int — position in seconds, or -1 if not a timed comment
 */
export interface CommentItem {
  authorName: string;
  authorUrl: string;
  authorAvatars: NativeImage[];
  authorVerified: boolean;
  commentId: string;
  /** Plain text from Description.content */
  commentText: string;
  publishedTime: string;
  /** Epoch seconds, 0 if unavailable */
  publishedTimestamp: number;
  likeCount: number;
  textualLikeCount: string;
  replyCount: number;
  /** Empty string when no replies available */
  repliesPageUrl: string;
  hasReplies: boolean;
  isPinned: boolean;
  isHearted: boolean;
  isChannelOwner: boolean;
  hasCreatorReply: boolean;
  streamPosition: number;
}

/** Returned by getComments() on first page (no pageUrl) */
export interface CommentsPage {
  success: boolean;
  disabled: boolean;
  commentsCount: number;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/** Returned by getComments() when a pageUrl is supplied */
export interface CommentsMorePage {
  success: boolean;
  comments: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface CommentRepliesPage {
  success: boolean;
  replies: CommentItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Search
// ─────────────────────────────────────────────

/**
 * Valid content filter tokens for YouTube per NewPipe SearchQueryHandlerFactory docs.
 *
 * Pass to search() as the filter param:
 *   ''             → no filter — returns all content types (videos, channels, playlists)
 *   'videos'       → video results only
 *   'channels'     → channel results only
 *   'playlists'    → playlist results only
 *   'music_songs'  → YouTube Music: songs
 *   'music_videos' → YouTube Music: music videos
 *   'music_albums' → YouTube Music: albums
 *   'music_playlists' → YouTube Music: playlists
 *
 * NOTE: 'all' is NOT a valid NewPipe filter token. Use '' (empty string) for
 * unfiltered search. Passing 'all' to Kotlin corrupts the search URL.
 */
export type YouTubeSearchFilter =
  | ''
  | 'videos'
  | 'channels'
  | 'playlists'
  | 'music_songs'
  | 'music_videos'
  | 'music_albums'
  | 'music_playlists';

export type SearchFilter = YouTubeSearchFilter | string;

/** Returned by search() on first page (no pageUrl) */
export interface SearchPage {
  success: boolean;
  query: string;
  suggestion: string;
  isCorrectedSearch: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/** Returned by search() when a pageUrl is supplied */
export interface SearchMorePage {
  success: boolean;
  results: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

export interface SearchFiltersResult {
  serviceId: number;
  serviceName: string;
  availableFilters: string[];
}

// ─────────────────────────────────────────────
// Playlist
// ─────────────────────────────────────────────

/**
 * Exact shape of extractPlaylistInfo() in Kotlin.
 * description comes from Description.content (@Nonnull in v0.26.0).
 * NO viewCount — PlaylistInfo has no view count in v0.26.0.
 */
export interface PlaylistInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  /** From Description.content */
  description: string;
  thumbnails: NativeImage[];
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatars: NativeImage[];
  streamCount: number;
  playlistType: string;
  nextPage: NativePage;
  hasNextPage: boolean;
  items: InfoItem[];
  errors: string[];
}

export interface PlaylistItemsPage {
  success: boolean;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

// ─────────────────────────────────────────────
// Channel
// ─────────────────────────────────────────────

/**
 * Exact shape of extractChannelInfo() in Kotlin.
 *
 * Key points:
 * - description is a plain String from ChannelExtractor.getDescription()
 *   which is @Nullable — Kotlin normalises null to "" via .orEmpty()
 * - NO viewCount, NO streamCount, NO nextPage — ChannelInfo extends Info
 *   not ListInfo in v0.26.0, so there is no pagination at this level
 * - tabs comes from ChannelInfo.tabs — a list of ListLinkHandler objects;
 *   use getChannelTabItems() to fetch items for a specific tab
 * - subscriberCount is Long, coerced to >= 0
 */
export interface ChannelInfo {
  success: boolean;
  serviceId: number;
  id: string;
  url: string;
  originalUrl: string;
  name: string;
  /** Plain String, @Nullable in extractor, normalised to "" */
  description: string;
  avatars: NativeImage[];
  banners: NativeImage[];
  feedUrl: string;
  subscriberCount: number;
  isVerified: boolean;
  tabs: ChannelTab[];
  errors: string[];
}

/**
 * A tab from ChannelInfo.tabs.
 * name is the first contentFilter string (e.g. "videos", "shorts", "playlists").
 * Pass name or any contentFilter value to getChannelTabItems() as tabFilter.
 */
export interface ChannelTab {
  name: string;
  contentFilters: string[];
  url: string;
}

export interface ChannelTabItemsPage {
  success: boolean;
  tabName: string;
  tabFilter: string;
  items: InfoItem[];
  nextPage: NativePage;
  hasNextPage: boolean;
  errors: string[];
}

/**
 * FeedInfo has no pagination in NewPipe v0.26.0 — getMoreItems() does not
 * exist on FeedInfo. The result is always a single page.
 */
export interface ChannelFeedResult {
  success: boolean;
  name: string;
  items: InfoItem[];
  errors: string[];
}

// ─────────────────────────────────────────────
// Kiosk
// ─────────────────────────────────────────────

export interface KioskEntry {
  id: string;
  name: string;
  url?: string;
  available: boolean;
  error?: string;
}

export interface KioskListResult {
  success: boolean;
  serviceId: number;
  /** defaultKioskId is non-null String in v0.26.0 — currently "Live" for YouTube */
  defaultKioskId: string;
  kiosks: KioskEntry[];
}

/**
 * Returned by getKioskInfo() on success.
 * If the requested kioskId does not exist (e.g. the removed "Trending" kiosk),
 * success will be false and items will be empty — no exception is thrown.
 */
export interface KioskPage {
  success: boolean;
  kioskId: string;
  name?: string;
  items: InfoItem[];
  nextPage?: NativePage;
  hasNextPage?: boolean;
  errors?: string[];
  /** Present only when success is false */
  error?: string;
  message?: string;
}

// ─────────────────────────────────────────────
// Trending — 6-layer fallback
// ─────────────────────────────────────────────

/**
 * All possible source strings from getTrendingWithFallback().
 *
 * Layer 1: "youtube_music_charts"         — FEmusic_charts InnerTube API
 * Layer 2: "innertube_browse"             — FEwhat_to_watch homepage feed
 * Layer 3: "kiosk_{id}"                  — e.g. "kiosk_trending_music"
 * Layer 4: "youtube_charts_html"          — charts.youtube.com HTML scrape
 * Layer 5: "innertube_next_recommendations" — Next API recommendations seed
 * Layer 6: "search_{year}"               — e.g. "search_2026"
 * Cache:   "cache"                        — in-memory 5-minute cache hit
 * Failure: "none"                         — all 6 layers failed
 */
export type TrendingSource =
  | 'youtube_music_charts'
  | 'innertube_browse'
  | `kiosk_${string}`
  | 'youtube_charts_html'
  | 'innertube_next_recommendations'
  | `search_${number}`
  | 'cache'
  | 'none';

export interface TrendingResult {
  success: boolean;
  /** Which layer provided the data */
  source: TrendingSource;
  /** Up to MAX_TRENDING_ITEMS (6) items */
  items: InfoItem[];
  /** Total items available before the 6-item cap */
  totalAvailable: number;
  /** Error messages from all failed layers */
  errors: string[];
  /** Present only when success is false */
  message?: string;
}

// ─────────────────────────────────────────────
// InnerTube config management
// ─────────────────────────────────────────────

export interface InnerTubeConfig {
  apiKey: string;
  clientVersion: string;
  musicClientVersion: string;
  /** Age of the cached config in milliseconds */
  cacheAge: number;
  isCached: boolean;
}

export interface InnerTubeRefreshResult {
  success: boolean;
  apiKey: string;
  clientVersion: string;
  musicClientVersion: string;
}

// ─────────────────────────────────────────────
// API key management
// ─────────────────────────────────────────────

export interface ApiKeyStatus {
  totalKeys: number;
  failedKeys: number;
  workingKeys: number;
  currentKeyIndex: number;
}

// ─────────────────────────────────────────────
// Trending cache management
// ─────────────────────────────────────────────

export interface TrendingCacheStatus {
  hasCachedData: boolean;
  cacheAgeMs: number;
  /** Always TRENDING_CACHE_TTL = 300_000 ms (5 minutes) */
  ttlMs: number;
  isValid: boolean;
}

// ─────────────────────────────────────────────
// URL utilities / deep linking
// ─────────────────────────────────────────────

/**
 * Returned by resolveUrl().
 * type is always lowercase: "stream" | "channel" | "playlist".
 *
 * Used for deep linking: receive any URL from a share sheet, call resolveUrl(),
 * then route to getStreamInfo / getChannelInfo / getPlaylistInfo based on type.
 */
export interface ResolvedUrl {
  type: 'stream' | 'channel' | 'playlist';
  id: string;
  url: string;
  serviceId: number;
  serviceName: string;
}

/**
 * Returned by canHandleUrl().
 * Both the serviceId path and the no-serviceId path now always return linkType.
 * serviceName is always present in both paths.
 * serviceId is -1 when no service can handle the URL and no serviceId was given.
 */
export interface CanHandleResult {
  canHandle: boolean;
  /** Lowercase link type: "stream" | "channel" | "playlist" | "none" */
  linkType: string;
  serviceId: number;
  serviceName: string;
  url: string;
}

/**
 * Returned by extractIdFromUrl().
 * type is always lowercase.
 */
export interface ExtractedId {
  id: string;
  type: 'stream' | 'channel' | 'playlist';
  url: string;
  serviceId: number;
}

// ─────────────────────────────────────────────
// Misc / utility types
// ─────────────────────────────────────────────

/**
 * ServiceInfo — mediaCapabilities comes from getMediaCapabilities() which
 * returns Set<MediaCapability> in v0.26.0 (breaking change from List in v0.25.x).
 * expo-modules-core serialises both Set and List as JS arrays, so the TS type
 * is unchanged.
 */
export interface ServiceInfo {
  id: number;
  name: string;
  baseUrl: string;
  mediaCapabilities: string[];
}

export interface PingResult {
  alive: boolean;
  version: string;
  timestamp: number;
}

export interface StreamUrlResult {
  success: boolean;
  url: string;
  format: string;
  title: string;
  duration: number;
  fallbackUrls: string[];
}

export interface AudioStreamsResult {
  success: boolean;
  title: string;
  audioStreams: AudioStream[];
}

export interface VideoStreamsResult {
  success: boolean;
  title: string;
  videoStreams: VideoStream[];
  videoOnlyStreams: VideoStream[];
}

export interface SubtitlesResult {
  success: boolean;
  title: string;
  subtitles: SubtitleStream[];
  availableLanguages: string[];
}

export interface VersionInfo {
  version: string;
  library: string;
  architecture: string;
  notes: string[];
}

export interface ResetResult {
  success: boolean;
  message: string;
}

// ═════════════════════════════════════════════════════════════════
// STREAM FUNCTIONS
// ═════════════════════════════════════════════════════════════════

export const getStreamInfo = (
  url: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfo(url, serviceId ?? null);

export const getStreamInfoById = (
  videoId: string,
  serviceId?: number
): Promise<StreamInfo> =>
  Native.getStreamInfoById(videoId, serviceId ?? null);

export const getStreamUrl = (
  url: string,
  format: 'audio' | 'video' | 'dash' | 'hls' | 'best' = 'best',
  serviceId?: number
): Promise<StreamUrlResult> =>
  Native.getStreamUrl(url, format, serviceId ?? null);

export const getAudioStreams = (
  url: string,
  serviceId?: number
): Promise<AudioStreamsResult> =>
  Native.getAudioStreams(url, serviceId ?? null);

export const getVideoStreams = (
  url: string,
  serviceId?: number
): Promise<VideoStreamsResult> =>
  Native.getVideoStreams(url, serviceId ?? null);

export const getSubtitles = (
  url: string,
  languageTag?: string,
  serviceId?: number
): Promise<SubtitlesResult> =>
  Native.getSubtitles(url, languageTag ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// COMMENTS
// ═════════════════════════════════════════════════════════════════

export const getComments = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<CommentsPage | CommentsMorePage> =>
  Native.getComments(url, pageUrl ?? null, serviceId ?? null);

export const getCommentReplies = (
  commentsUrl: string,
  repliesPageUrl: string,
  serviceId?: number
): Promise<CommentRepliesPage> =>
  Native.getCommentReplies(commentsUrl, repliesPageUrl, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// SEARCH
// ═════════════════════════════════════════════════════════════════

/**
 * Search for content across a service.
 *
 * filter defaults to "all" (YoutubeSearchQueryHandlerFactory.ALL).
 * Valid YouTube filters: "all" | "videos" | "channels" | "playlists" |
 * "music_songs" | "music_videos" | "music_albums" | "music_playlists"
 *
 * Passing null or undefined for filter also resolves to "all" in the
 * Kotlin layer via the YoutubeSearchQueryHandlerFactory.ALL default.
 */
/**
 * Search for content on a service.
 *
 * filter: leave blank ('') for all content types. Per NewPipe API docs,
 *   an empty contentFilter list means no filter. The string 'all' is NOT
 *   a valid NewPipe filter — always use '' for unfiltered results.
 *
 * Valid YouTube filters: 'videos' | 'channels' | 'playlists' |
 *   'music_songs' | 'music_videos' | 'music_albums' | 'music_playlists'
 *
 * serviceId: omit or pass undefined for YouTube (0 = default).
 *   Kotlin receives null and applies NewPipe.getService(0).
 */
export const search = (
  query: string,
  filter: SearchFilter = '',
  pageUrl?: string,
  serviceId?: number
): Promise<SearchPage | SearchMorePage> => {
  if (!query?.trim()) {
    return Promise.reject(new Error('Search query cannot be empty'));
  }
  // Pass filter as-is. '' means no filter (all results) per NewPipe API.
  // Pass null for serviceId when not specified — Kotlin defaults to YouTube (0).
  return Native.search(query.trim(), filter, pageUrl ?? null, serviceId ?? null);
};

export const getSearchSuggestions = (
  query: string,
  serviceId?: number
): Promise<string[]> =>
  Native.getSearchSuggestions(query, serviceId ?? null);

export const getSearchFilters = (
  serviceId?: number
): Promise<SearchFiltersResult> =>
  Native.getSearchFilters(serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// PLAYLIST
// ═════════════════════════════════════════════════════════════════

export const getPlaylistInfo = (
  url: string,
  serviceId?: number
): Promise<PlaylistInfo> =>
  Native.getPlaylistInfo(url, serviceId ?? null);

export const getPlaylistItems = (
  url: string,
  pageUrl?: string,
  serviceId?: number
): Promise<PlaylistItemsPage> =>
  Native.getPlaylistItems(url, pageUrl ?? null, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// CHANNEL
// ═════════════════════════════════════════════════════════════════

/**
 * Fetches full channel metadata including the tabs list.
 * The response includes a tabs array — use getChannelTabItems() to load
 * items for a specific tab. There is no separate getChannelTabs() function;
 * tabs were removed as a redundant network call in the Kotlin refactor.
 */
export const getChannelInfo = (
  url: string,
  serviceId?: number
): Promise<ChannelInfo> =>
  Native.getChannelInfo(url, serviceId ?? null);

/**
 * Fetch items for a specific channel tab.
 * tabFilter should match a value from ChannelTab.contentFilters
 * (e.g. "videos", "shorts", "playlists", "livestreams").
 * Pass an empty string to get the first available tab.
 */
export const getChannelTabItems = (
  url: string,
  tabFilter: string,
  pageUrl?: string,
  serviceId?: number
): Promise<ChannelTabItemsPage> =>
  Native.getChannelTabItems(url, tabFilter, pageUrl ?? null, serviceId ?? null);

/**
 * Fetch items via the channel's RSS/Atom feed when available.
 * FeedInfo has no pagination in v0.26.0 — this always returns a single page.
 * Falls back cleanly if the service/channel has no feed.
 */
export const getChannelFeed = (
  url: string,
  serviceId?: number
): Promise<ChannelFeedResult> =>
  Native.getChannelFeed(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// KIOSK
// ═════════════════════════════════════════════════════════════════

export const getKioskList = (
  serviceId?: number
): Promise<KioskListResult> =>
  Native.getKioskList(serviceId ?? null);

/**
 * Fetch items for a kiosk by ID.
 * The Kotlin layer validates the kioskId against availableKiosks before
 * calling getExtractorById — an invalid ID returns success: false rather
 * than throwing. The removed "Trending" kiosk is handled this way.
 *
 * Valid YouTube kiosk IDs in v0.26.0:
 * "Live" | "trending_music" | "trending_gaming" |
 * "trending_movies_and_shows" | "trending_podcasts_episodes"
 */
export const getKioskInfo = (
  kioskId: string,
  pageUrl?: string,
  serviceId?: number
): Promise<KioskPage> =>
  Native.getKioskInfo(kioskId, pageUrl ?? null, serviceId ?? null);

/**
 * @deprecated Routed internally to getTrendingWithFallback("music").
 * Use getTrendingWithFallback() directly for explicit control over category
 * and to inspect which fallback layer provided the data.
 */
export const getTrending = (serviceId?: number): Promise<TrendingResult> =>
  Native.getTrending(serviceId ?? null);

/**
 * @deprecated Routed internally to getTrendingWithFallback("videos").
 * Use getTrendingWithFallback() directly.
 */
export const getMostPopular = (serviceId?: number): Promise<TrendingResult> =>
  Native.getMostPopular(serviceId ?? null);

/**
 * Fetch a specific YouTube kiosk by a friendly type name.
 * The Kotlin layer normalises the input to the correct kiosk ID:
 *   "trending" → "trending_music"  (global Trending was removed July 2025)
 *   "music"    → "trending_music"
 *   "gaming"   → "trending_gaming"
 *   "movies"   → "trending_movies_and_shows"
 *   "podcasts" → "trending_podcasts_episodes"
 *   "live"     → "Live"
 *
 * @deprecated For trending content, prefer getTrendingWithFallback() which
 * uses a 6-layer fallback and is resilient to kiosk availability changes.
 */
export const getYouTubeKiosk = (
  kioskType:
    | 'live' | 'Live'
    | 'trending' | 'Trending'
    | 'music' | 'trending_music'
    | 'gaming' | 'trending_gaming'
    | 'movies' | 'trending_movies' | 'trending_movies_and_shows'
    | 'podcasts' | 'trending_podcasts' | 'trending_podcasts_episodes',
  serviceId: number = 0
): Promise<KioskPage> =>
  Native.getYouTubeKiosk(kioskType, serviceId);

// ═════════════════════════════════════════════════════════════════
// TRENDING — 6-LAYER FALLBACK
// ═════════════════════════════════════════════════════════════════

/**
 * Fetch trending content with a 6-layer fallback strategy.
 * This is the recommended way to get trending content since YouTube
 * removed the global Trending page on 2025-07-21.
 *
 * Layer 1: YouTube Music Charts InnerTube (FEmusic_charts) — primary
 * Layer 2: InnerTube Browse (FEwhat_to_watch) — homepage feed
 * Layer 3: NewPipe sub-kiosks (trending_music, trending_gaming, etc.)
 * Layer 4: YouTube Charts HTML scraping (charts.youtube.com)
 * Layer 5: InnerTube Next API recommendations seed
 * Layer 6: Search fallback ("trending music official video {year}")
 *
 * Results are cached for 5 minutes. Check result.source to see which
 * layer provided the data, and result.errors for any failed layers.
 *
 * @param category - "music" | "gaming" | "movies" | "podcast" | "videos" | any string
 * @param serviceId - Service ID (default 0 = YouTube)
 */
export const getTrendingWithFallback = (
  category: 'music' | 'gaming' | 'movies' | 'podcast' | 'videos' | string = 'music',
  serviceId?: number
): Promise<TrendingResult> =>
  Native.getTrendingWithFallback(category, serviceId ?? 0);

// ═════════════════════════════════════════════════════════════════
// INNERTUBE CONFIG MANAGEMENT
// ═════════════════════════════════════════════════════════════════

/**
 * Read the current InnerTube config (API key + client versions).
 * Config is fetched live from YouTube's homepage and cached for 24 hours.
 */
export const getInnerTubeConfig = (): Promise<InnerTubeConfig> =>
  Native.getInnerTubeConfig();

/**
 * Force a refresh of the InnerTube config, bypassing the 24-hour cache.
 */
export const refreshInnerTubeConfig = (): Promise<InnerTubeRefreshResult> =>
  Native.refreshInnerTubeConfig();

// ═════════════════════════════════════════════════════════════════
// API KEY MANAGEMENT
// ═════════════════════════════════════════════════════════════════

/** Read the current state of the InnerTube API key rotation pool. */
export const getApiKeyStatus = (): Promise<ApiKeyStatus> =>
  Native.getApiKeyStatus();

/** Clear the failed keys list and reset rotation to key index 0. */
export const resetFailedKeys = (): Promise<{ success: boolean }> =>
  Native.resetFailedKeys();

// ═════════════════════════════════════════════════════════════════
// TRENDING CACHE MANAGEMENT
// ═════════════════════════════════════════════════════════════════

/** Clear the 5-minute trending cache, forcing the next call to re-fetch. */
export const clearTrendingCache = (): Promise<{ success: boolean }> =>
  Native.clearTrendingCache();

/** Read the current state of the trending cache. */
export const getTrendingCacheStatus = (): Promise<TrendingCacheStatus> =>
  Native.getTrendingCacheStatus();

// ═════════════════════════════════════════════════════════════════
// URL UTILITIES / DEEP LINKING
// ═════════════════════════════════════════════════════════════════

/**
 * Resolve a URL to its content type, canonical ID, and service.
 *
 * Deep linking pattern:
 *   const resolved = await resolveUrl(sharedUrl);
 *   if (resolved.type === 'stream')   → getStreamInfo(resolved.url)
 *   if (resolved.type === 'channel')  → getChannelInfo(resolved.url)
 *   if (resolved.type === 'playlist') → getPlaylistInfo(resolved.url)
 *
 * Throws if the URL cannot be handled or the link type cannot be determined.
 * getLinkTypeByUrl() exceptions are caught and re-thrown with a clear message.
 * Null channel/playlist factories (services that don't support them) are
 * also caught and re-thrown with a descriptive error.
 */
export const resolveUrl = (
  url: string,
  serviceId?: number
): Promise<ResolvedUrl> =>
  Native.resolveUrl(url, serviceId ?? null);

/**
 * Check whether any registered service can handle a URL.
 * Never throws — returns canHandle: false on errors.
 *
 * Both the serviceId and no-serviceId paths return the same shape,
 * including linkType. serviceName is always present.
 */
export const canHandleUrl = (
  url: string,
  serviceId?: number
): Promise<CanHandleResult> =>
  Native.canHandleUrl(url, serviceId ?? null);

/**
 * Extract just the canonical content ID from a URL.
 * Lighter-weight than resolveUrl when you only need the ID.
 * Throws on unhandled URLs or null factories.
 */
export const extractIdFromUrl = (
  url: string,
  serviceId?: number
): Promise<ExtractedId> =>
  Native.extractIdFromUrl(url, serviceId ?? null);

// ═════════════════════════════════════════════════════════════════
// MODULE PROPERTIES
// ═════════════════════════════════════════════════════════════════

/** Current module version string, e.g. "8.1.0" */
export const version: string = Native.version;

/** Whether NewPipe has been successfully initialised */
export const initialized: boolean = Native.initialized;

/**
 * List of all registered streaming services.
 * mediaCapabilities returns as a string array (Set<MediaCapability> in v0.26.0,
 * serialised by expo-modules-core the same as a List).
 */
export const services: ServiceInfo[] = Native.services;

// ═════════════════════════════════════════════════════════════════
// UTILITY FUNCTIONS
// ═════════════════════════════════════════════════════════════════

export const ping = (): Promise<PingResult> =>
  Native.ping();

/**
 * Tear down NewPipe and re-initialise from scratch.
 * Also clears the trending cache, InnerTube config cache, and key rotation state.
 */
export const emergencyReset = (): Promise<ResetResult> =>
  Native.emergencyReset();

export const getVersion = (): Promise<VersionInfo> =>
  Native.getVersion();

// ═════════════════════════════════════════════════════════════════
// DEFAULT EXPORT
// ═════════════════════════════════════════════════════════════════

const MavinEngine = {
  // Properties
  version,
  initialized,
  services,

  // Stream
  getStreamInfo,
  getStreamInfoById,
  getStreamUrl,
  getAudioStreams,
  getVideoStreams,
  getSubtitles,

  // Comments
  getComments,
  getCommentReplies,

  // Search
  search,
  getSearchSuggestions,
  getSearchFilters,

  // Playlist
  getPlaylistInfo,
  getPlaylistItems,

  // Channel
  getChannelInfo,
  getChannelTabItems,
  getChannelFeed,

  // Kiosk
  getKioskList,
  getKioskInfo,
  /** @deprecated Use getTrendingWithFallback() */
  getTrending,
  /** @deprecated Use getTrendingWithFallback() */
  getMostPopular,
  /** @deprecated Use getTrendingWithFallback() */
  getYouTubeKiosk,

  // Trending
  getTrendingWithFallback,

  // InnerTube config
  getInnerTubeConfig,
  refreshInnerTubeConfig,

  // Key management
  getApiKeyStatus,
  resetFailedKeys,

  // Trending cache
  clearTrendingCache,
  getTrendingCacheStatus,

  // Deep linking
  resolveUrl,
  canHandleUrl,
  extractIdFromUrl,

  // Utility
  ping,
  emergencyReset,
  getVersion,
};

export default MavinEngine;