@file:Suppress("unused", "MemberVisibilityCanBePrivate")
package expo.modules.mavinengine

import android.content.Context
import android.util.Log
import expo.modules.kotlin.exception.CodedException
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import org.schabi.newpipe.extractor.*
import org.schabi.newpipe.extractor.channel.ChannelInfo
import org.schabi.newpipe.extractor.channel.ChannelInfoItem
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabInfo
import org.schabi.newpipe.extractor.comments.CommentsInfo
import org.schabi.newpipe.extractor.comments.CommentsInfoItem
import org.schabi.newpipe.extractor.downloader.Downloader
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.exceptions.*
import org.schabi.newpipe.extractor.feed.FeedInfo
import org.schabi.newpipe.extractor.kiosk.KioskInfo
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import org.schabi.newpipe.extractor.playlist.PlaylistInfo
import org.schabi.newpipe.extractor.playlist.PlaylistInfoItem
import org.schabi.newpipe.extractor.search.SearchInfo
import org.schabi.newpipe.extractor.stream.*
import org.schabi.newpipe.extractor.stream.StreamType.*
import java.io.IOException
import java.util.Locale
import java.util.concurrent.TimeUnit

/**
 * MavinEngine — NewPipe Extractor v0.26.0 Integration
 * All API calls verified against official Javadoc:
 * https://teamnewpipe.github.io/NewPipeExtractor/javadoc/
 *
 * Key v0.26.0 facts applied:
 *  - Service.getMediaCapabilities() returns Set<MediaCapability> (not List)
 *  - AudioStream.getBitrate() and VideoStream.getBitrate() are the correct methods
 *    (getAverageBitrate() was removed in v0.22.0)
 *  - AudioStream: getAudioTrackId(), getAudioTrackName(), getAudioLocale(), getAudioTrackType()
 *  - VideoStream: getWidth(), getHeight(), getFps(), getBitrate(), getQuality()
 *  - SubtitlesStream: getLanguageTag(), isAutoGenerated, displayLanguageName
 *  - StreamInfo fields accessed via getter methods (not direct field access)
 *  - Description.getContent() (not .content)
 *  - Page: getUrl(), getIds(), getCookies(), getBody() are the correct getter methods
 *  - StreamInfo.getContentAvailability() returns ContentAvailability enum
 *  - CommentsInfoItem.getReplies() returns a Page? (nullable)
 *  - StreamInfo.getInfo(StreamExtractor) calls fetchPage() internally — no pre-fetch needed
 *  - FeedInfo has no pagination (no getMoreItems) in v0.26.0
 *  - ChannelTabInfo.getInfo(service, ListLinkHandler) — takes ListLinkHandler, not String
 *  - KioskInfo.getInfo(service, url) and getMoreItems(service, url, Page) — url is a String
 */
class MavinEngineModule : Module() {
    private val context: Context
        get() = requireNotNull(appContext.reactContext) { "React context unavailable" }

    companion object {
        private const val TAG = "MavinEngine"
        private const val VERSION = "6.1.0"
        private val httpClient = OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(45, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .retryOnConnectionFailure(true)
            .build()
        @Volatile
        private var isInitialized = false
    }

    override fun definition() = ModuleDefinition {
        Name("MavinEngine")

        Property("version").get<String> { VERSION }
        Property("initialized").get<Boolean> { isInitialized }
        // NOTE: getMediaCapabilities() returns Set<MediaCapability> in v0.26.0
        Property("services").get<List<Map<String, Any>>> { getServicesList() }

        OnCreate { initializeNewPipe() }

        // ── Streams ──────────────────────────────────────────────────────────
        AsyncFunction("getStreamInfo") { url: String, serviceId: Int? ->
            ensureInit()
            extractStreamInfo(url, serviceId)
        }
        AsyncFunction("getStreamInfoById") { videoId: String, serviceId: Int? ->
            ensureInit()
            extractStreamInfoById(videoId, serviceId)
        }
        AsyncFunction("getStreamUrl") { url: String, format: String?, serviceId: Int? ->
            ensureInit()
            getBestStreamUrl(url, format ?: "best", serviceId)
        }
        AsyncFunction("getAudioStreams") { url: String, serviceId: Int? ->
            ensureInit()
            extractAudioStreams(url, serviceId)
        }
        AsyncFunction("getVideoStreams") { url: String, serviceId: Int? ->
            ensureInit()
            extractVideoStreams(url, serviceId)
        }
        AsyncFunction("getSubtitles") { url: String, language: String?, serviceId: Int? ->
            ensureInit()
            extractSubtitles(url, language, serviceId)
        }

        // ── Comments ─────────────────────────────────────────────────────────
        AsyncFunction("getComments") { url: String, pageUrl: String?, serviceId: Int? ->
            ensureInit()
            extractComments(url, pageUrl, serviceId)
        }
        AsyncFunction("getCommentReplies") { commentsUrl: String, repliesPageUrl: String, serviceId: Int? ->
            ensureInit()
            extractCommentReplies(commentsUrl, repliesPageUrl, serviceId)
        }

        // ── Search ───────────────────────────────────────────────────────────
        AsyncFunction("search") { query: String, filter: String?, pageUrl: String?, serviceId: Int? ->
            ensureInit()
            performSearch(query, filter ?: "all", pageUrl, serviceId)
        }
        AsyncFunction("getSearchSuggestions") { query: String, serviceId: Int? ->
            ensureInit()
            getSearchSuggestions(query, serviceId)
        }
        AsyncFunction("getSearchFilters") { serviceId: Int? ->
            ensureInit()
            getAvailableSearchFilters(serviceId)
        }

        // ── Playlist ─────────────────────────────────────────────────────────
        AsyncFunction("getPlaylistInfo") { url: String, serviceId: Int? ->
            ensureInit()
            extractPlaylistInfo(url, serviceId)
        }
        AsyncFunction("getPlaylistItems") { url: String, pageUrl: String?, serviceId: Int? ->
            ensureInit()
            extractPlaylistItems(url, pageUrl, serviceId)
        }

        // ── Channel ──────────────────────────────────────────────────────────
        AsyncFunction("getChannelInfo") { url: String, serviceId: Int? ->
            ensureInit()
            extractChannelInfo(url, serviceId)
        }
        AsyncFunction("getChannelTabs") { url: String, serviceId: Int? ->
            ensureInit()
            extractChannelTabs(url, serviceId)
        }
        AsyncFunction("getChannelTabItems") { url: String, tabFilter: String, pageUrl: String?, serviceId: Int? ->
            ensureInit()
            extractChannelTabItems(url, tabFilter, pageUrl, serviceId)
        }
        AsyncFunction("getChannelFeed") { url: String, serviceId: Int? ->
            ensureInit()
            extractChannelFeed(url, serviceId)
        }

        // ── Kiosk (Trending / Most Popular) ──────────────────────────────────
        AsyncFunction("getKioskList") { serviceId: Int? ->
            ensureInit()
            listAvailableKiosks(serviceId)
        }
        AsyncFunction("getKioskInfo") { kioskId: String, pageUrl: String?, serviceId: Int? ->
            ensureInit()
            extractKioskInfo(kioskId, pageUrl, serviceId)
        }
        AsyncFunction("getTrending") { serviceId: Int? ->
            ensureInit()
            extractKioskInfo("Trending", null, serviceId)
        }
        AsyncFunction("getMostPopular") { serviceId: Int? ->
            ensureInit()
            extractKioskInfo("Live", null, serviceId)
        }
        AsyncFunction("getYouTubeKiosk") { kioskType: String, serviceId: Int? ->
            ensureInit()
            val id = when (kioskType.uppercase()) {
                "LIVE"     -> "Live"
                "MUSIC"    -> "Music"
                "GAMING"   -> "Gaming"
                "MOVIES"   -> "Movies"
                "TRENDING" -> "Trending"
                else       -> "Trending"
            }
            extractKioskInfo(id, null, serviceId ?: 0)
        }

        // ── URL Utilities ────────────────────────────────────────────────────
        AsyncFunction("resolveUrl") { url: String, serviceId: Int? ->
            ensureInit()
            resolveUrl(url, serviceId)
        }
        AsyncFunction("canHandleUrl") { url: String, serviceId: Int? ->
            ensureInit()
            checkCanHandle(url, serviceId)
        }
        AsyncFunction("extractIdFromUrl") { url: String, serviceId: Int? ->
            ensureInit()
            extractIdFromUrl(url, serviceId)
        }

        // ── Utility ──────────────────────────────────────────────────────────
        AsyncFunction("ping") {
            mapOf<String, Any>(
                "alive"     to true,
                "version"   to VERSION,
                "timestamp" to System.currentTimeMillis()
            )
        }
        AsyncFunction("emergencyReset") { resetNewPipe() }
        AsyncFunction("getVersion") {
            mapOf<String, Any>(
                "version"      to VERSION,
                "library"      to "NewPipeExtractor 0.26.0",
                "releaseNotes" to "https://github.com/TeamNewPipe/NewPipeExtractor/releases/tag/v0.26.0"
            )
        }
    }

    // ── Initialization ──────────────────────────────────────────────────────

    private fun initializeNewPipe() {
        if (isInitialized) return
        synchronized(this) {
            if (isInitialized) return
            try {
                NewPipe.init(
                    MavinDownloader(httpClient),
                    Localization.fromLocale(Locale.US),
                    ContentCountry("US")
                )
                isInitialized = true
                Log.i(TAG, "✅ NewPipe v0.26.0 initialized — ${ServiceList.all().size} services loaded")
            } catch (e: Exception) {
                Log.e(TAG, "NewPipe init failed", e)
                throw CodedException("INIT_FAILED", "NewPipe.init failed: ${e.message}", e)
            }
        }
    }

    private fun ensureInit() {
        if (!isInitialized) initializeNewPipe()
    }

    private fun resetNewPipe(): Map<String, Any> {
        isInitialized = false
        initializeNewPipe()
        return mapOf("success" to true, "message" to "NewPipe reset and re-initialised")
    }

    // ── Service Resolution ──────────────────────────────────────────────────

    private fun getService(serviceId: Int): StreamingService {
        return ServiceList.all().firstOrNull { it.serviceId == serviceId }
            ?: throw ExtractionException("No service with id=$serviceId")
    }

    private fun getDefaultService(): StreamingService {
        return ServiceList.all().firstOrNull { it.serviceId == 0 }
            ?: ServiceList.all().firstOrNull()
            ?: throw ExtractionException("No streaming services registered")
    }

    private fun getServiceForUrl(url: String): StreamingService {
        return ServiceList.all().firstOrNull { service ->
            try {
                service.getLinkTypeByUrl(url) != StreamingService.LinkType.NONE
            } catch (_: Exception) { false }
        } ?: throw ExtractionException("No service can handle URL: $url")
    }

    private fun resolveService(url: String, serviceId: Int?): StreamingService =
        if (serviceId != null) getService(serviceId) else getServiceForUrl(url)

    /**
     * In v0.26.0 getMediaCapabilities() returns Set<MediaCapability>, not List.
     * We call .map { } on it safely since Set is Iterable.
     */
    private fun getServicesList(): List<Map<String, Any>> {
        if (!isInitialized) return emptyList()
        return ServiceList.all().map { s ->
            mapOf<String, Any>(
                "id"                to s.serviceId,
                "name"              to s.serviceInfo.name,
                "baseUrl"           to (s.baseUrl ?: ""),
                // getMediaCapabilities() → Set<MediaCapability> in v0.26.0
                "mediaCapabilities" to s.serviceInfo.mediaCapabilities.map { it.name }
            )
        }
    }

    // ── Stream Extraction ───────────────────────────────────────────────────

    /**
     * StreamInfo.getInfo(StreamExtractor) fetches the page internally.
     * Do NOT call extractor.fetchPage() before it — that would double-fetch.
     * Signature: StreamInfo.getInfo(@Nonnull StreamExtractor extractor)
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractStreamInfo(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val extractor = service.getStreamExtractor(url)
        val info = StreamInfo.getInfo(extractor)          // fetches page internally
        return streamInfoToMap(info, service.serviceId)
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractStreamInfoById(videoId: String, serviceId: Int?): Map<String, Any> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        val linkHandler = service.streamLHFactory.fromId(videoId)
        val extractor = service.getStreamExtractor(linkHandler)
        val info = StreamInfo.getInfo(extractor)          // fetches page internally
        return streamInfoToMap(info, service.serviceId)
    }

    /**
     * StreamInfo field access reference (all are getter methods):
     *  - info.name                → info.getName() in Java; in Kotlin property access is fine
     *  - info.uploaderName        → getter
     *  - info.uploaderUrl         → getter
     *  - info.uploaderAvatars     → getter, returns List<Image>
     *  - info.isUploaderVerified  → isUploaderVerified() getter (boolean)
     *  - info.uploaderSubscriberCount → getter, returns long (-1 if unknown)
     *  - info.duration            → getter, returns long
     *  - info.viewCount           → getter, returns long (-1 if unknown)
     *  - info.likeCount           → getter, returns long (-1 if unknown)
     *  - info.dislikeCount        → getter, returns long (-1 if unknown)
     *  - info.description         → getter, returns Description object
     *  - info.description.content → Description.getContent() in Java → .content in Kotlin
     *  - info.uploadDate          → getter, returns DateWrapper? (nullable)
     *  - info.textualUploadDate   → getter, returns String?
     *  - info.thumbnails          → getter, returns List<Image>
     *  - info.streamType          → getter, returns StreamType enum
     *  - info.isShortFormContent  → isShortFormContent() getter (boolean)
     *  - info.getContentAvailability() → returns ContentAvailability enum
     *  - info.ageLimit            → getter, returns int
     *  - info.tags                → getter, returns List<String>
     *  - info.category            → getter, returns String?
     *  - info.audioStreams        → getter, returns List<AudioStream>
     *  - info.videoStreams        → getter, returns List<VideoStream>
     *  - info.videoOnlyStreams    → getter, returns List<VideoStream>
     *  - info.dashMpdUrl          → getter, returns String
     *  - info.hlsUrl              → getter, returns String
     *  - info.subtitles           → getter, returns List<SubtitlesStream>
     *  - info.relatedItems        → getter, returns List<InfoItem>
     *  - info.metaInfo            → getter, returns List<MetaInfo>
     *
     *  DateWrapper.offsetDateTime() was replaced by .date() returning Instant in v0.25.0+.
     *  Use uploadDate?.date?.toString() safely.
     */
    // Use buildMap to avoid Kotlin type-inference failure on large heterogeneous mapOf blocks
    private fun streamInfoToMap(info: StreamInfo, serviceId: Int): Map<String, Any> =
        buildMap<String, Any> {
            put("success",                 true)
            put("serviceId",               serviceId)
            put("id",                      info.id)
            put("url",                     info.url)
            put("originalUrl",             info.originalUrl)
            put("title",                   info.name.orEmpty())
            put("uploaderName",            info.uploaderName.orEmpty())
            put("uploaderUrl",             info.uploaderUrl.orEmpty())
            put("uploaderAvatars",         info.uploaderAvatars.map { imageToMap(it) })
            put("uploaderVerified",        info.isUploaderVerified)
            // uploaderSubscriberCount returns -1 when unknown; clamp to 0 for JS consumers
            put("uploaderSubscriberCount", info.uploaderSubscriberCount.coerceAtLeast(0))
            put("duration",                info.duration)
            put("viewCount",               info.viewCount.coerceAtLeast(0))
            put("likeCount",               info.likeCount.coerceAtLeast(0))
            put("dislikeCount",            info.dislikeCount.coerceAtLeast(0))
            // Description.content is the plain-text accessor in Kotlin (getContent() in Java)
            put("description",             info.description.content)
            put("uploadDate",              info.uploadDate?.offsetDateTime()?.toString() ?: "")
            put("textualUploadDate",       info.textualUploadDate.orEmpty())
            put("thumbnails",              info.thumbnails.map { imageToMap(it) })
            put("streamType",              info.streamType.name)
            put("isLive",                  info.streamType == LIVE_STREAM || info.streamType == AUDIO_LIVE_STREAM)
            put("isShortFormContent",      info.isShortFormContent)
            // getContentAvailability() returns ContentAvailability enum
            put("availability",            info.getContentAvailability().name)
            put("ageLimit",                info.ageLimit)
            put("tags",                    info.tags)
            put("category",                info.category.orEmpty())
            put("audioStreams",            info.audioStreams.map { audioStreamToMap(it) })
            put("videoStreams",            info.videoStreams.map { videoStreamToMap(it) })
            put("videoOnlyStreams",        info.videoOnlyStreams.map { videoStreamToMap(it) })
            put("dashMpdUrl",              info.dashMpdUrl.orEmpty())
            put("hlsUrl",                  info.hlsUrl.orEmpty())
            put("subtitles",               info.subtitles.map { subtitleToMap(it) })
            put("relatedItems",            info.relatedItems.take(20).mapNotNull { infoItemToMap(it) })
            put("metaInfo",                info.metaInfo.map { m ->
                mapOf<String, Any>(
                    "title"    to m.title.orEmpty(),
                    "content"  to m.content.content,
                    "urls"     to m.urls.map { it.toString() },
                    "urlTexts" to m.urlTexts
                )
            })
        }

    @Throws(ExtractionException::class, IOException::class)
    private fun getBestStreamUrl(url: String, format: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val extractor = service.getStreamExtractor(url)
        val info = StreamInfo.getInfo(extractor)
        // AudioStream.getBitrate() and VideoStream.getBitrate() — correct in v0.26.0
        val best = when (format.lowercase()) {
            "audio", "mp3", "m4a", "ogg" ->
                info.audioStreams.maxByOrNull { it.getBitrate() }?.content
            "video", "mp4", "best" ->
                info.videoStreams.maxByOrNull { it.getHeight() }?.content
                    ?: info.videoOnlyStreams.maxByOrNull { it.getHeight() }?.content
            "dash" -> info.dashMpdUrl.takeIf { it.isNotEmpty() }
            "hls"  -> info.hlsUrl.takeIf { it.isNotEmpty() }
            else   -> info.audioStreams.maxByOrNull { it.getBitrate() }?.content
        }
        return mapOf<String, Any>(
            "success"      to (best != null),
            "url"          to (best ?: ""),
            "format"       to format,
            "title"        to info.name.orEmpty(),
            "duration"     to info.duration,
            "fallbackUrls" to listOfNotNull(
                info.dashMpdUrl.takeIf { it.isNotEmpty() },
                info.hlsUrl.takeIf { it.isNotEmpty() }
            )
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractAudioStreams(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = StreamInfo.getInfo(service.getStreamExtractor(url))
        return mapOf<String, Any>(
            "success"      to true,
            "title"        to info.name.orEmpty(),
            "audioStreams"  to info.audioStreams.map { audioStreamToMap(it) }
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractVideoStreams(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = StreamInfo.getInfo(service.getStreamExtractor(url))
        return mapOf<String, Any>(
            "success"          to true,
            "title"            to info.name.orEmpty(),
            "videoStreams"     to info.videoStreams.map { videoStreamToMap(it) },
            "videoOnlyStreams" to info.videoOnlyStreams.map { videoStreamToMap(it) }
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractSubtitles(url: String, language: String?, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = StreamInfo.getInfo(service.getStreamExtractor(url))
        val all = info.subtitles
        val filtered = if (language.isNullOrBlank()) all
                       else all.filter { it.getLanguageTag().equals(language, ignoreCase = true) }
        return mapOf<String, Any>(
            "success"            to true,
            "title"              to info.name.orEmpty(),
            "subtitles"          to filtered.map { subtitleToMap(it) },
            "availableLanguages" to all.map { it.getLanguageTag() }.distinct()
        )
    }

    // ── Comments ────────────────────────────────────────────────────────────

    /**
     * CommentsInfo.getInfo(StreamingService, String) — correct signature.
     * CommentsInfo.getMoreItems(StreamingService, String, Page) — correct signature.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractComments(url: String, pageUrl: String?, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        return if (pageUrl.isNullOrEmpty()) {
            val info = CommentsInfo.getInfo(service, url)
            mapOf<String, Any>(
                "success"       to true,
                "disabled"      to info.isCommentsDisabled,
                "commentsCount" to info.commentsCount,
                "comments"      to info.relatedItems.map { commentItemToMap(it) },
                "nextPage"      to pageOrEmpty(info.nextPage),
                "hasNextPage"   to (info.nextPage != null),
                "errors"        to info.errors.map { it.message.orEmpty() }
            )
        } else {
            val more = CommentsInfo.getMoreItems(service, url, Page(pageUrl))
            mapOf<String, Any>(
                "success"     to true,
                "comments"    to more.items.map { commentItemToMap(it) },
                "nextPage"    to pageOrEmpty(more.nextPage),
                "hasNextPage" to (more.nextPage != null),
                "errors"      to more.errors.map { it.message.orEmpty() }
            )
        }
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractCommentReplies(
        commentsUrl: String,
        repliesPageUrl: String,
        serviceId: Int?
    ): Map<String, Any> {
        val service = resolveService(commentsUrl, serviceId)
        val page = CommentsInfo.getMoreItems(service, commentsUrl, Page(repliesPageUrl))
        return mapOf<String, Any>(
            "success"     to true,
            "replies"     to page.items.map { commentItemToMap(it) },
            "nextPage"    to pageOrEmpty(page.nextPage),
            "hasNextPage" to (page.nextPage != null),
            "errors"      to page.errors.map { it.message.orEmpty() }
        )
    }

    /**
     * CommentsInfoItem field/method reference:
     *  - uploaderName, uploaderUrl, uploaderAvatars  → getters
     *  - isUploaderVerified                          → isUploaderVerified() getter
     *  - commentId                                   → getCommentId()
     *  - commentText                                 → getCommentText() returns Description
     *  - textualUploadDate                           → getTextualUploadDate()
     *  - uploadDate                                  → getUploadDate() returns DateWrapper?
     *  - likeCount                                   → getLikeCount() returns int
     *  - textualLikeCount                            → getTextualLikeCount()
     *  - replyCount                                  → getReplyCount() returns int
     *  - getReplies()                                → returns Page? (nullable)
     *  - isPinned                                    → isPinned() getter
     *  - isHeartedByUploader                         → isHeartedByUploader() getter
     *  - isChannelOwner                              → isChannelOwner() getter
     *  - hasCreatorReply()                           → method (added in extractor changelog)
     *  - streamPosition                              → getStreamPosition() returns int
     */
    private fun commentItemToMap(item: CommentsInfoItem): Map<String, Any> = mapOf<String, Any>(
        "authorName"        to item.uploaderName.orEmpty(),
        "authorUrl"         to item.uploaderUrl.orEmpty(),
        "authorAvatars"     to item.uploaderAvatars.map { imageToMap(it) },
        "authorVerified"    to item.isUploaderVerified,
        "commentId"         to item.commentId.orEmpty(),
        "commentText"       to item.commentText.content,
        "publishedTime"     to item.textualUploadDate.orEmpty(),
        "publishedTimestamp" to (item.uploadDate?.offsetDateTime()?.toEpochSecond() ?: 0L),
        "likeCount"         to item.likeCount.coerceAtLeast(0),
        "textualLikeCount"  to item.textualLikeCount.orEmpty(),
        "replyCount"        to item.replyCount,
        // getReplies() returns a Page? — use safe call and getUrl() on the Page
        "repliesPageUrl"    to (item.getReplies()?.getUrl() ?: ""),
        "hasReplies"        to (item.replyCount > 0 || item.getReplies() != null),
        "isPinned"          to item.isPinned,
        "isHearted"         to item.isHeartedByUploader,
        "isChannelOwner"    to item.isChannelOwner,
        "hasCreatorReply"   to item.hasCreatorReply(),
        "streamPosition"    to item.streamPosition
    )

    // ── Search ──────────────────────────────────────────────────────────────

    /**
     * SearchInfo.getInfo(StreamingService, SearchQueryHandler) — correct signature.
     * SearchInfo.getMoreItems(StreamingService, SearchQueryHandler, Page) — correct signature.
     * service.searchQHFactory.fromQuery(query, contentFilter, sortFilter) — correct.
     * service.searchQHFactory.availableContentFilter — returns array of filter strings.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun performSearch(
        query: String,
        filter: String,
        pageUrl: String?,
        serviceId: Int?
    ): Map<String, Any> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        val handler = service.searchQHFactory.fromQuery(query, listOf(filter), "")
        return if (pageUrl.isNullOrEmpty()) {
            val info = SearchInfo.getInfo(service, handler)
            mapOf<String, Any>(
                "success"          to true,
                "query"            to info.searchString.orEmpty(),
                "suggestion"       to info.searchSuggestion.orEmpty(),
                "isCorrectedSearch" to info.isCorrectedSearch,
                "results"          to info.relatedItems.mapNotNull { infoItemToMap(it) },
                "nextPage"         to pageOrEmpty(info.nextPage),
                "hasNextPage"      to (info.nextPage != null),
                "errors"           to info.errors.map { it.message.orEmpty() }
            )
        } else {
            val more = SearchInfo.getMoreItems(service, handler, Page(pageUrl))
            mapOf<String, Any>(
                "success"     to true,
                "results"     to more.items.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(more.nextPage),
                "hasNextPage" to (more.nextPage != null),
                "errors"      to more.errors.map { it.message.orEmpty() }
            )
        }
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun getSearchSuggestions(query: String, serviceId: Int?): List<String> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        return service.getSuggestionExtractor().suggestionList(query)
    }

    private fun getAvailableSearchFilters(serviceId: Int?): Map<String, Any> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        return mapOf<String, Any>(
            "serviceId"        to service.serviceId,
            "serviceName"      to service.serviceInfo.name,
            // availableContentFilter returns Array<String>
            "availableFilters" to service.searchQHFactory.availableContentFilter.toList()
        )
    }

    // ── Playlist ────────────────────────────────────────────────────────────

    /**
     * PlaylistInfo.getInfo(StreamingService, String) — correct signature.
     * PlaylistInfo.getMoreItems(StreamingService, String, Page) — correct signature.
     * NOTE: PlaylistInfo has NO viewCount field in v0.26.0.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractPlaylistInfo(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = PlaylistInfo.getInfo(service, url)
        return mapOf<String, Any>(
            "success"        to true,
            "serviceId"      to service.serviceId,
            "id"             to info.id,
            "url"            to info.url,
            "originalUrl"    to info.originalUrl,
            "name"           to info.name.orEmpty(),
            "description"    to info.description.content,
            "thumbnails"     to info.thumbnails.map { imageToMap(it) },
            "uploaderName"   to info.uploaderName.orEmpty(),
            "uploaderUrl"    to info.uploaderUrl.orEmpty(),
            "uploaderAvatars" to info.uploaderAvatars.map { imageToMap(it) },
            "streamCount"    to info.streamCount.coerceAtLeast(0),
            "playlistType"   to (info.playlistType?.name ?: "NORMAL"),
            "nextPage"       to pageOrEmpty(info.nextPage),
            "hasNextPage"    to (info.nextPage != null),
            "items"          to info.relatedItems.mapNotNull { infoItemToMap(it) },
            "errors"         to info.errors.map { it.message.orEmpty() }
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractPlaylistItems(url: String, pageUrl: String?, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        return if (pageUrl.isNullOrEmpty()) {
            val info = PlaylistInfo.getInfo(service, url)
            mapOf<String, Any>(
                "success"     to true,
                "items"       to info.relatedItems.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(info.nextPage),
                "hasNextPage" to (info.nextPage != null),
                "errors"      to info.errors.map { it.message.orEmpty() }
            )
        } else {
            val more = PlaylistInfo.getMoreItems(service, url, Page(pageUrl))
            mapOf<String, Any>(
                "success"     to true,
                "items"       to more.items.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(more.nextPage),
                "hasNextPage" to (more.nextPage != null),
                "errors"      to more.errors.map { it.message.orEmpty() }
            )
        }
    }

    // ── Channel ─────────────────────────────────────────────────────────────

    /**
     * ChannelInfo.getInfo(StreamingService, String) — correct signature.
     * ChannelInfo fields: name, description, avatars, banners, feedUrl,
     *   subscriberCount, isVerified, tabs (List<ListLinkHandler>), nextPage, errors.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractChannelInfo(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = ChannelInfo.getInfo(service, url)
        return mapOf<String, Any>(
            "success"         to true,
            "serviceId"       to service.serviceId,
            "id"              to info.id,
            "url"             to info.url,
            "originalUrl"     to info.originalUrl,
            "name"            to info.name.orEmpty(),
            "description"     to info.description.orEmpty(),
            "avatars"         to info.avatars.map { imageToMap(it) },
            "banners"         to info.banners.map { imageToMap(it) },
            "feedUrl"         to info.feedUrl.orEmpty(),
            "subscriberCount" to info.subscriberCount.coerceAtLeast(0),
            "isVerified"      to info.isVerified,
            "tabs"            to info.tabs.map { tabLinkHandlerToMap(it) },
            "nextPage"        to pageOrEmpty(info.nextPage),
            "errors"          to info.errors.map { it.message.orEmpty() }
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractChannelTabs(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val info = ChannelInfo.getInfo(service, url)
        return mapOf<String, Any>(
            "success"     to true,
            "channelName" to info.name.orEmpty(),
            "tabs"        to info.tabs.map { tabLinkHandlerToMap(it) }
        )
    }

    /**
     * ListLinkHandler (tab) fields:
     *  - contentFilters: List<String>
     *  - url: String
     *  (no separate "name" field; the filter string IS the tab identifier)
     */
    private fun tabLinkHandlerToMap(tab: ListLinkHandler): Map<String, Any> = mapOf<String, Any>(
        "name"           to (tab.contentFilters.firstOrNull() ?: ""),
        "contentFilters" to tab.contentFilters,
        "url"            to tab.url
    )

    /**
     * ChannelTabInfo.getInfo(StreamingService, ListLinkHandler) — takes ListLinkHandler, NOT a URL string.
     * ChannelTabInfo.getMoreItems(StreamingService, ListLinkHandler, Page) — same.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractChannelTabItems(
        channelUrl: String,
        tabFilter: String,
        pageUrl: String?,
        serviceId: Int?
    ): Map<String, Any> {
        val service = resolveService(channelUrl, serviceId)
        val channelInfo = ChannelInfo.getInfo(service, channelUrl)
        val targetTab = if (tabFilter.isBlank()) {
            channelInfo.tabs.firstOrNull()
        } else {
            channelInfo.tabs.firstOrNull { tab ->
                tab.contentFilters.any { it.equals(tabFilter, ignoreCase = true) }
            }
        } ?: throw ExtractionException("No tab matching filter '$tabFilter'")

        return if (pageUrl.isNullOrEmpty()) {
            val tabInfo = ChannelTabInfo.getInfo(service, targetTab)
            mapOf<String, Any>(
                "success"     to true,
                "tabName"     to (targetTab.contentFilters.firstOrNull() ?: ""),
                "tabFilter"   to tabFilter,
                "items"       to tabInfo.relatedItems.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(tabInfo.nextPage),
                "hasNextPage" to (tabInfo.nextPage != null),
                "errors"      to tabInfo.errors.map { it.message.orEmpty() }
            )
        } else {
            val more = ChannelTabInfo.getMoreItems(service, targetTab, Page(pageUrl))
            mapOf<String, Any>(
                "success"     to true,
                "tabName"     to (targetTab.contentFilters.firstOrNull() ?: ""),
                "tabFilter"   to tabFilter,
                "items"       to more.items.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(more.nextPage),
                "hasNextPage" to (more.nextPage != null),
                "errors"      to more.errors.map { it.message.orEmpty() }
            )
        }
    }

    /**
     * FeedInfo is NOT paginated in v0.26.0 — there is no getMoreItems().
     * FeedInfo.getInfo(FeedExtractor) — correct.
     * Removed pageUrl parameter as it has no effect.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun extractChannelFeed(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val feedExtractor = service.getFeedExtractor(url)
            ?: return mapOf<String, Any>(
                "success" to false,
                "error"   to "NO_FEED",
                "message" to "No feed available for this service/channel"
            )
        val feedInfo = FeedInfo.getInfo(feedExtractor)
        return mapOf<String, Any>(
            "success" to true,
            "name"    to feedInfo.name.orEmpty(),
            "items"   to feedInfo.relatedItems.mapNotNull { infoItemToMap(it) },
            "errors"  to feedInfo.errors.map { it.message.orEmpty() }
        )
    }

    // ── Kiosk ───────────────────────────────────────────────────────────────

    /**
     * KioskList.getExtractorById(kioskId, Page?) — second param is Page? (null for first page), NOT Localization.
     * KioskExtractor.url — gives the URL string.
     * KioskInfo.getInfo(StreamingService, String) — String is the kiosk URL.
     * KioskInfo.getMoreItems(StreamingService, String, Page) — String is the kiosk URL.
     */
    @Throws(ExtractionException::class, IOException::class)
    private fun listAvailableKiosks(serviceId: Int?): Map<String, Any> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        val kioskList = service.kioskList
        val ids = kioskList.availableKiosks
        // Use mutableMapOf per entry to avoid Kotlin mixed-type inference failure in try/catch
        // getExtractorById(String, Page?) — second param is Page?, not Localization; pass null
        val kioskEntries: List<Map<String, Any>> = ids.map { id ->
            val entry = mutableMapOf<String, Any>()
            try {
                val extractor = kioskList.getExtractorById(id, null)
                entry["id"]        = id
                entry["name"]      = extractor.name
                entry["url"]       = extractor.url
                entry["available"] = true
            } catch (e: Exception) {
                entry["id"]        = id
                entry["name"]      = id
                entry["available"] = false
                entry["error"]     = e.message ?: ""
            }
            entry
        }
        return mapOf<String, Any>(
            "success"        to true,
            "serviceId"      to service.serviceId,
            "defaultKioskId" to (kioskList.defaultKioskId ?: ""),
            "kiosks"         to kioskEntries
        )
    }

    @Throws(ExtractionException::class, IOException::class)
    private fun extractKioskInfo(kioskId: String, pageUrl: String?, serviceId: Int?): Map<String, Any> {
        val service = if (serviceId != null) getService(serviceId) else getDefaultService()
        // getExtractorById(String, Page?) — second param is Page?, not Localization; pass null
        val kioskExtractor = service.kioskList.getExtractorById(kioskId, null)
        val kioskUrl = kioskExtractor.url

        return if (pageUrl.isNullOrEmpty()) {
            val info = KioskInfo.getInfo(service, kioskUrl)
            mapOf<String, Any>(
                "success"     to true,
                "kioskId"     to kioskId,
                "name"        to info.name.orEmpty(),
                "items"       to info.relatedItems.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(info.nextPage),
                "hasNextPage" to (info.nextPage != null),
                "errors"      to info.errors.map { it.message.orEmpty() }
            )
        } else {
            val more = KioskInfo.getMoreItems(service, kioskUrl, Page(pageUrl))
            mapOf<String, Any>(
                "success"     to true,
                "kioskId"     to kioskId,
                "items"       to more.items.mapNotNull { infoItemToMap(it) },
                "nextPage"    to pageOrEmpty(more.nextPage),
                "hasNextPage" to (more.nextPage != null),
                "errors"      to more.errors.map { it.message.orEmpty() }
            )
        }
    }

    // ── URL Utilities ───────────────────────────────────────────────────────

    @Throws(ExtractionException::class)
    private fun resolveUrl(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val linkType = service.getLinkTypeByUrl(url)
        val id = when (linkType) {
            StreamingService.LinkType.STREAM   -> service.streamLHFactory.fromUrl(url).id
            StreamingService.LinkType.CHANNEL  -> service.channelLHFactory.fromUrl(url).id
            StreamingService.LinkType.PLAYLIST -> service.playlistLHFactory.fromUrl(url).id
            StreamingService.LinkType.NONE     -> throw ExtractionException("URL not handled: $url")
        }
        return mapOf<String, Any>(
            "type"        to linkType.name.lowercase(),
            "id"          to id,
            "url"         to url,
            "serviceId"   to service.serviceId,
            "serviceName" to service.serviceInfo.name
        )
    }

    @Throws(ExtractionException::class)
    private fun checkCanHandle(url: String, serviceId: Int?): Map<String, Any> {
        if (serviceId != null) {
            val service = getService(serviceId)
            val linkType = service.getLinkTypeByUrl(url)
            return mapOf<String, Any>(
                "canHandle"  to (linkType != StreamingService.LinkType.NONE),
                "linkType"   to linkType.name.lowercase(),
                "serviceId"  to service.serviceId,
                "url"        to url
            )
        }
        val match = ServiceList.all().firstOrNull { s ->
            try { s.getLinkTypeByUrl(url) != StreamingService.LinkType.NONE } catch (_: Exception) { false }
        }
        return mapOf<String, Any>(
            "canHandle"   to (match != null),
            "serviceId"   to (match?.serviceId ?: -1),
            "serviceName" to (match?.serviceInfo?.name ?: ""),
            "url"         to url
        )
    }

    @Throws(ExtractionException::class)
    private fun extractIdFromUrl(url: String, serviceId: Int?): Map<String, Any> {
        val service = resolveService(url, serviceId)
        val linkType = service.getLinkTypeByUrl(url)
        val id = when (linkType) {
            StreamingService.LinkType.STREAM   -> service.streamLHFactory.fromUrl(url).id
            StreamingService.LinkType.CHANNEL  -> service.channelLHFactory.fromUrl(url).id
            StreamingService.LinkType.PLAYLIST -> service.playlistLHFactory.fromUrl(url).id
            StreamingService.LinkType.NONE     -> throw ExtractionException("Cannot extract ID: $url")
        }
        return mapOf<String, Any>(
            "id"        to id,
            "type"      to linkType.name.lowercase(),
            "url"       to url,
            "serviceId" to service.serviceId
        )
    }

    // ── InfoItem mapping ────────────────────────────────────────────────────

    /**
     * InfoItem subtype dispatch.
     * StreamInfoItem fields: serviceId, url, name, uploaderName, uploaderUrl,
     *   isUploaderVerified, thumbnails, duration, viewCount, textualUploadDate,
     *   streamType, isShortFormContent.
     * PlaylistInfoItem fields: serviceId, url, name, uploaderName, uploaderUrl,
     *   thumbnails, streamCount, playlistType.
     * ChannelInfoItem fields: serviceId, url, name, thumbnails, subscriberCount,
     *   streamCount, isVerified, description.
     */
    private fun infoItemToMap(item: InfoItem): Map<String, Any>? = when (item) {
        is StreamInfoItem -> mapOf<String, Any>(
            "type"              to "stream",
            "serviceId"         to item.serviceId,
            "url"               to item.url,
            "name"              to item.name.orEmpty(),
            "uploaderName"      to item.uploaderName.orEmpty(),
            "uploaderUrl"       to item.uploaderUrl.orEmpty(),
            "uploaderVerified"  to item.isUploaderVerified,
            "thumbnails"        to item.thumbnails.map { imageToMap(it) },
            "duration"          to (item.duration ?: 0L),
            "viewCount"         to (item.viewCount ?: 0L),
            "textualUploadDate" to item.textualUploadDate.orEmpty(),
            "streamType"        to item.streamType.name,
            "isLive"            to (item.streamType == LIVE_STREAM || item.streamType == AUDIO_LIVE_STREAM),
            "isShortFormContent" to item.isShortFormContent
        )
        is PlaylistInfoItem -> mapOf<String, Any>(
            "type"         to "playlist",
            "serviceId"    to item.serviceId,
            "url"          to item.url,
            "name"         to item.name.orEmpty(),
            "uploaderName" to item.uploaderName.orEmpty(),
            "uploaderUrl"  to item.uploaderUrl.orEmpty(),
            "thumbnails"   to item.thumbnails.map { imageToMap(it) },
            "streamCount"  to (item.streamCount ?: 0L),
            "playlistType" to (item.playlistType?.name ?: "NORMAL")
        )
        is ChannelInfoItem -> mapOf<String, Any>(
            "type"            to "channel",
            "serviceId"       to item.serviceId,
            "url"             to item.url,
            "name"            to item.name.orEmpty(),
            "thumbnails"      to item.thumbnails.map { imageToMap(it) },
            "subscriberCount" to (item.subscriberCount ?: 0L),
            "streamCount"     to (item.streamCount ?: 0L),
            "isVerified"      to item.isVerified,
            "description"     to item.description.orEmpty()
        )
        else -> null
    }

    // ── Stream field mapping ────────────────────────────────────────────────

    /**
     * AudioStream method reference (v0.26.0):
     *  - content (Stream.content)          → getContent() — the URL or manifest body
     *  - isUrl (Stream.isUrl)              → isUrl() getter
     *  - deliveryMethod                    → getDeliveryMethod() returns DeliveryMethod enum
     *  - format                            → getFormat() returns MediaFormat?
     *  - codec                             → getCodec() returns String?
     *  - getBitrate()                      → int; was renamed from getAverageBitrate() (removed in v0.22.0)
     *  - getAudioTrackId()                 → String?
     *  - getAudioTrackName()               → String?
     *  - getAudioLocale()                  → Locale?
     *  - getAudioTrackType()               → AudioTrackType? (may be null)
     *  - manifestUrl (Stream.manifestUrl)  → getManifestUrl() returns String?
     */
    private fun audioStreamToMap(s: AudioStream): Map<String, Any> = mapOf<String, Any>(
        "url"              to (s.content ?: ""),
        "isUrl"            to s.isUrl,
        "deliveryMethod"   to s.deliveryMethod.name,
        "format"           to (s.format?.name ?: ""),
        "codec"            to (s.codec ?: ""),
        // getBitrate() is correct — getAverageBitrate() does not exist in v0.26.0
        "bitrate"          to s.getBitrate(),
        "audioTrackId"     to (s.getAudioTrackId() ?: ""),
        "audioTrackName"   to (s.getAudioTrackName() ?: ""),
        "audioLocale"      to (s.getAudioLocale()?.toLanguageTag() ?: ""),
        // getAudioTrackType() returns AudioTrackType enum or null
        "audioTrackType"   to (s.getAudioTrackType()?.name ?: ""),
        "manifestUrl"      to (s.manifestUrl ?: "")
    )

    /**
     * VideoStream method reference (v0.26.0):
     *  - content           → getContent()
     *  - isUrl             → isUrl()
     *  - deliveryMethod    → getDeliveryMethod()
     *  - format            → getFormat() returns MediaFormat?
     *  - codec             → getCodec() returns String?
     *  - getWidth()        → int
     *  - getHeight()       → int
     *  - getFps()          → int
     *  - getBitrate()      → int (VideoStream also uses getBitrate(), not getAverageBitrate())
     *  - getQuality()      → String (e.g. "720p")
     *  - manifestUrl       → getManifestUrl() returns String?
     */
    private fun videoStreamToMap(s: VideoStream): Map<String, Any> = mapOf<String, Any>(
        "url"            to (s.content ?: ""),
        "isUrl"          to s.isUrl,
        "deliveryMethod" to s.deliveryMethod.name,
        "format"         to (s.format?.name ?: ""),
        "codec"          to (s.codec ?: ""),
        "width"          to s.getWidth(),
        "height"         to s.getHeight(),
        "fps"            to s.getFps(),
        "bitrate"        to s.getBitrate(),
        "quality"        to s.getQuality(),
        "manifestUrl"    to (s.manifestUrl ?: "")
    )

    /**
     * SubtitlesStream method reference (v0.26.0):
     *  - content               → getContent()
     *  - isUrl                 → isUrl()
     *  - deliveryMethod        → getDeliveryMethod()
     *  - format                → getFormat() returns MediaFormat?
     *  - getLanguageTag()      → String (BCP-47 language tag)
     *  - displayLanguageName   → getDisplayLanguageName() returns String?
     *  - isAutoGenerated       → isAutoGenerated() getter
     *  - manifestUrl           → getManifestUrl() returns String?
     */
    private fun subtitleToMap(s: SubtitlesStream): Map<String, Any> = mapOf<String, Any>(
        "url"                 to (s.content ?: ""),
        "isUrl"               to s.isUrl,
        "deliveryMethod"      to s.deliveryMethod.name,
        "format"              to (s.format?.name ?: ""),
        "languageTag"         to s.getLanguageTag(),
        "displayLanguageName" to (s.displayLanguageName ?: ""),
        "isAutoGenerated"     to s.isAutoGenerated,
        "manifestUrl"         to (s.manifestUrl ?: "")
    )

    /**
     * Image field reference:
     *  - url                      → String
     *  - width                    → int
     *  - height                   → int
     *  - estimatedResolutionLevel → Image.ResolutionLevel enum
     */
    private fun imageToMap(img: Image): Map<String, Any> = mapOf<String, Any>(
        "url"             to img.url,
        "width"           to img.width,
        "height"          to img.height,
        "resolutionLevel" to img.estimatedResolutionLevel.name
    )

    /**
     * Page method reference (v0.26.0):
     *  - Page(String url)                  — constructor taking a URL string
     *  - Page(String url, List<String> ids, Map<String,String> cookies) — full constructor
     *  - getUrl()                          → String?
     *  - getIds()                          → List<String>?
     *  - getCookies()                      → Map<String,String>?
     *  - getBody()                         → byte[]?
     *
     * All are nullable-safe getters; use ?: for null-safety.
     */
    // Helper to avoid Kotlin type-inference failure with nullable Page in mapOf blocks
    private fun pageOrEmpty(p: Page?): Map<String, Any> =
        p?.let { pageToMap(it) } ?: emptyMap()

    private fun pageToMap(p: Page): Map<String, Any> = mapOf<String, Any>(
        "url"     to (p.getUrl() ?: ""),
        "ids"     to (p.getIds() ?: emptyList<String>()),
        "cookies" to (p.getCookies() ?: emptyMap<String, String>())
    )

    // ── Downloader ──────────────────────────────────────────────────────────

    /**
     * Downloader.execute(Request) — the single method to implement.
     * Request methods: url(), httpMethod(), headers(), dataToSend().
     * Response constructor: Response(int responseCode, String responseMessage,
     *   Map<String,List<String>> headers, @Nullable String responseBody,
     *   @Nullable String latestUrl)
     */
    class MavinDownloader(private val client: OkHttpClient) : Downloader() {
        @Throws(IOException::class, ExtractionException::class)
        override fun execute(request: org.schabi.newpipe.extractor.downloader.Request): Response {
            val builder = Request.Builder().url(request.url())
            when (request.httpMethod()) {
                "POST" -> {
                    val body = request.dataToSend()
                    builder.post(
                        if (body != null)
                            RequestBody.create(
                                "application/x-www-form-urlencoded".toMediaTypeOrNull(),
                                body
                            )
                        else
                            RequestBody.create(null, ByteArray(0))
                    )
                }
                "HEAD" -> builder.head()
                else   -> builder.get()
            }
            val headers = request.headers()
            if (!headers.containsKey("User-Agent")) {
                builder.addHeader(
                    "User-Agent",
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
                        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                )
            }
            headers.forEach { (key, values) ->
                values.forEach { value -> builder.addHeader(key, value) }
            }
            val okResponse = client.newCall(builder.build()).execute()
            val responseBody = okResponse.body?.string() ?: ""
            val responseHeaders = okResponse.headers.toMultimap()
            return Response(
                okResponse.code,
                okResponse.message,
                responseHeaders,
                responseBody,
                okResponse.request.url.toString()
            )
        }
    }
}